Properly cast blank in python, test to_python_type()
quadratichq/quadratic pull request #1190
Opened 2024-03-15 18:57 UTC by ddimaria

- [x] Override "blank" value, cast based on usage
- [x] Test to_python_type()

 
![Screenshot 2024-03-15 at 12 57 18 PM](https://github.com/quadratichq/quadratic/assets/1536436/38950666-7421-42af-9388-8ea3c231b17f)

2024-03-15 20:13 UTC, davidkircos commented on quadratic-kernels/python-wasm/tests/test.py
> +        assert to_python_type("", "blank") == 0
I think we use `self.assert()` instead of the built-in assertions 

@Asaaj do you know if it matters?

2024-03-15 20:17 UTC, Asaaj commented on quadratic-kernels/python-wasm/tests/test.py
> +        assert to_python_type("", "blank") == 0
The only real difference is that the `assert` keyword is optimized out in "optimized" mode, but I don't run tests with that flag because that's kind of useless. I used `assert` because that's what I'm used to, I forgot you were using `unittest` instead of `pytest`

2024-03-15 22:19 UTC, davidkircos commented on quadratic-kernels/python-wasm/tests/test.py
> +        assert to_python_type("-1", "number") == -1
duplicates

2024-03-15 22:19 UTC, davidkircos commented on quadratic-kernels/python-wasm/tests/test.py
> +        assert to_python_type("False", "logical") == False
duplicates. try diffent casing

2024-03-15 22:20 UTC, davidkircos commented on quadratic-kernels/python-wasm/tests/test.py
> +        assert to_python_type("1352518200", "instant") == pd.Timestamp("2012-11-10 03:30:00")
duplicates

2024-03-15 22:27 UTC, ddimaria commented on quadratic-kernels/python-wasm/tests/test.py
> +        assert to_python_type("False", "logical") == False
Done

2024-03-15 22:27 UTC, ddimaria commented on quadratic-kernels/python-wasm/tests/test.py
> +        assert to_python_type("1352518200", "instant") == pd.Timestamp("2012-11-10 03:30:00")
Removed

2024-03-15 22:28 UTC, ddimaria commented on quadratic-kernels/python-wasm/tests/test.py
> +        assert to_python_type("-1", "number") == -1
Done

2024-03-15 22:40 UTC, davidkircos requested changes
remove `quadratic-client/.env.sentry-build-plugin`

2024-03-15 22:58 UTC, davidkircos approved these changes

2024-03-18 15:14 UTC, davidkircos approved these changes

2024-03-18 15:31 UTC, merged