Inline formula
quadratichq/quadratic pull request #1316
Opened 2024-04-25 17:32 UTC by davidfig

- [x] replace CellInput with InputEditor
- [ ] width should adjust automatically based on the width of the content
- [ ] div should never scroll or move from its anchor position
- [ ] formula should be activated with `=` as the first character w/proper syntax highlighting and hinting
- [ ] bold and italic support

2024-05-02 15:32 UTC, ddimaria commented on quadratic-client/src/app/gridGL/HTMLGrid/inlineEditor/inlineEditorFormula.ts
> +      this.decorations?.clear();
Maybe call `clearDecorations()` here instead (if turning off the dirty flag is OK)?

2024-05-02 15:35 UTC, ddimaria commented on quadratic-client/src/app/gridGL/HTMLGrid/inlineEditor/inlineEditorHandler.ts
> +      throw new Error('Expected div and editor to be defined in InlineEditorHandler');
Sentry?

2024-05-02 15:36 UTC, ddimaria commented on quadratic-client/src/app/gridGL/HTMLGrid/inlineEditor/inlineEditorHandler.ts
> +        window.removeEventListener('keydown', inlineEditorKeyboard.keyDown);
Is this necessary?

2024-05-02 15:37 UTC, ddimaria commented on quadratic-client/src/app/gridGL/HTMLGrid/inlineEditor/inlineEditorHandler.ts
> +        throw new Error('Expected formulaExpandDiv to be defined in InlineEditorHandler');
Same here.  Call Sentry or recover from this error via code?

2024-05-02 15:42 UTC, ddimaria commented on quadratic-client/src/app/gridGL/HTMLGrid/inlineEditor/inlineEditorMonaco.ts
> +  private getModel(): editor.ITextModel {
We have this code all over the place in the codebase. We should consider abstracting it at some point.

2024-05-02 15:45 UTC, ddimaria commented on quadratic-client/src/app/gridGL/UI/Cursor.ts
> +          : colors.independence;
Is this last default value OK for the SQL connector cursor?

2024-05-02 15:47 UTC, ddimaria reviewed
Code review is complete.

2024-05-02 16:00 UTC, davidfig commented on quadratic-client/src/app/gridGL/HTMLGrid/inlineEditor/inlineEditorHandler.ts
> +        window.removeEventListener('keydown', inlineEditorKeyboard.keyDown);
Yes. We need to add/remove the keyboard listening event when the inline editor is hidden (b/c we're on a different sheet) but we still want to get the keyboard events.

2024-05-02 16:01 UTC, davidfig commented on quadratic-client/src/app/gridGL/UI/Cursor.ts
> +          : colors.independence;
No. The last default should never occur. We'll need to add colors for SQL since we're still in colorland (Jim is against colorland).

2024-05-03 12:25 UTC, davidfig commented on quadratic-client/src/app/gridGL/HTMLGrid/inlineEditor/inlineEditorFormula.ts
> +        throw new Error('Expected inlineEditorHandler.location to be defined in cursorMoved');
Doesn't Sentry capture all unhandled exceptions?

2024-05-03 12:25 UTC, davidfig commented on quadratic-client/src/app/gridGL/HTMLGrid/inlineEditor/inlineEditorFormula.ts
> +        throw new Error('Expected inlineEditorHandler.location to be defined in cursorMoved');
See https://docs.sentry.io/product/sentry-basics/integrate-backend/capturing-errors/

2024-05-06 14:18 UTC, ddimaria commented on quadratic-client/src/app/gridGL/HTMLGrid/inlineEditor/inlineEditorFormula.ts
> +  async closeParentheses(): Promise<string | undefined> {
Offload to Rust?

2024-05-07 12:04 UTC, davidfig commented on quadratic-client/src/app/gridGL/HTMLGrid/inlineEditor/inlineEditorFormula.ts
> +  async closeParentheses(): Promise<string | undefined> {
Not worth the effort. It uses a naive approach without parsing.

2024-05-07 17:38 UTC, davidkircos commented
Icon update by @jimniels

2024-05-07 20:34 UTC, jimniels commented
It can happen where you get the inline formula editor _and_ the multi-line code editor open at the same time, in which case they fall out of sync with each other.

https://github.com/quadratichq/quadratic/assets/1316441/9b672552-8deb-474a-9ab1-be46915c8018

2024-05-07 20:55 UTC, jimniels commented on quadratic-client/src/app/gridGL/HTMLGrid/inlineEditor/InlineEditor.tsx
> +                // TODO: davidf: something is resetting the height when this renders
@davidfig can you help? something is resetting the height on this and idk what it is

![image](https://github.com/quadratichq/quadratic/assets/1316441/a84934c6-c933-4807-aaa8-86dc36a14fe8)

2024-05-16 20:14 UTC, davidkircos requested changes
Bug:
Start an inline formula, type something, expand to full editor.
While the inline editor is still open, press / on a different cell. Select Python
The content from the inline formula will appear in the python formula

2024-05-20 17:59 UTC, jimniels commented
When using Google Sheets or Excel, you can select multiple cells at once is done by holding the CMD key and then clicking on individual cells


https://github.com/quadratichq/quadratic/assets/1316441/87028bde-5d47-4997-b8af-bb84e7520901

Quadratic does not do this. Holding down CMD and clicking doesn't make multiple selections. It only moves the selection.


https://github.com/quadratichq/quadratic/assets/1316441/5bb64ef1-dd8d-40e6-b7f6-bebb231a12c6

Seems like we should match the functionality of excel/sheets.

2024-05-20 18:07 UTC, jimniels commented
When you delete the last closing parenthesis, then try to make a selection with the cursor, it seems to cancel your entire selection and breaks you out of interactive editing mode — presumably because it inserts the cell reference at the beginning of the cell

https://github.com/quadratichq/quadratic/assets/1316441/95f3804f-ddba-44a6-806b-be9d2fed539e

Google docs doesn't do this.

https://github.com/quadratichq/quadratic/assets/1316441/b608bec6-9d6b-47e5-99df-a9834c721bf1

2024-05-20 18:34 UTC, jimniels commented
Seems a bit odd that the cell outlines disappear _before_ I've changed anything in my formula.

https://github.com/quadratichq/quadratic/assets/1316441/f480c1b9-cc77-4f30-96d3-89b06a76f8ae

We don't do that with other cell types (like python). Seems like the outlines should stay _until_ the formula re-runs.

2024-05-21 18:21 UTC, jimniels approved these changes
I'm 👍  on the functionality of this

2024-05-21 18:43 UTC, davidkircos approved these changes

2024-05-21 18:44 UTC, merged