Drag cells to move
quadratichq/quadratic pull request #1332
Opened 2024-05-03 19:09 UTC by davidfig

- [x] hover in the top-left corner of the cursor origin shows a drag cursor
- [x] click on that corner starts a move
- [x] during cell moving, the floating context menu is hidden
- [x] show UI (skeleton box) when dragging cell
- [x] cancel move on escape
- [ ] cut-and-paste cells when releasing move
- [ ] moving to the viewport borders scrolls the viewport

2024-05-06 14:25 UTC, ddimaria commented on quadratic-client/src/app/gridGL/UI/UICellMoving.ts
> +        default:
Is this state possible?

2024-05-06 14:30 UTC, ddimaria commented on quadratic-client/src/app/ui/menus/ContextMenu/FloatingContextMenu.tsx
> +  const [_, setTrigger] = useState(0);
Why set the value if it's never read?

2024-05-06 14:34 UTC, ddimaria commented on quadratic-core/src/controller/execution/execute_operation/execute_move_cells.rs
> +            // if !transaction.is_user() || transaction.is_undo_redo() {
Remove?

2024-05-06 14:35 UTC, ddimaria commented on quadratic-core/src/controller/operations/clipboard.rs
> +        vec![Operation::MoveCells { source, dest }]
Nice, very efficient operation 💯

2024-05-06 14:38 UTC, ddimaria commented on quadratic-core/src/grid/sheet/code.rs
> +            .iter_mut()
This may not need to be mutable.

2024-05-06 14:39 UTC, ddimaria commented on quadratic-core/src/grid/sheet/code.rs
> +        pos.iter()
Are you able to keep this as a single iterator, or was Rust complaining about not knowing types?

2024-05-06 14:40 UTC, ddimaria approved these changes
Code looks good.

2024-05-06 15:45 UTC, ddimaria commented
Rust lint is failing. Also, this branch is out of date with main.

2024-05-07 12:06 UTC, davidfig commented on quadratic-client/src/app/gridGL/UI/UICellMoving.ts
> +        default:
Yes. state has three settings: move, hover, and undefined. default is undefined

2024-05-07 12:06 UTC, davidfig commented on quadratic-client/src/app/ui/menus/ContextMenu/FloatingContextMenu.tsx
> +  const [_, setTrigger] = useState(0);
It forces a rerender for the component and triggered by pixi, which is vanilla so doesn't work perfectly with react.

2024-05-07 12:08 UTC, davidfig commented on quadratic-core/src/controller/execution/execute_operation/execute_move_cells.rs
> +            // if !transaction.is_user() || transaction.is_undo_redo() {
Yes, thanks. This was my original attempt to recreate the move operation w/o relying on cut/paste. It would have taken too much effort. Ideally, we'd have better functions that work across clipboard and move. But we don't (probably my fault). Something to fix down the road.

2024-05-08 16:27 UTC, davidkircos requested changes
![CleanShot 2024-05-08 at 09 42 19@2x](https://github.com/quadratichq/quadratic/assets/3479421/adf9b390-3aca-4564-bcfe-960ecfe49beb)

Red dot visible when resizing

2024-05-13 16:13 UTC, davidkircos approved these changes

2024-05-13 16:14 UTC, merged