feat: multiline ai assist prompts
quadratichq/quadratic pull request #1346
Opened 2024-05-11 21:26 UTC by AyushAgrawal-A2

closes #1210 

Changes:
- Added Textarea component which can auto grow unto a max height, used this for AI assist promts. Max height is currently set to 120px, configurable via props.
- Fixed auto focus of prompt input on selecting AI assistant tab.

[ai assist prompt input.webm](https://github.com/quadratichq/quadratic/assets/54364088/98940367-27ce-40a9-a5c4-e304bebcbca5)

2024-05-20 19:56 UTC, jimniels requested changes

2024-05-20 19:56 UTC, jimniels commented on quadratic-client/src/shared/shadcn/ui/textarea.tsx
> +        {...props}
There's a lot of duplication going on in this base component. `authHeight`, `onChange`, and `onKeyDown` all seem to be re-implementing what you're already doing with `<Textarea>` in the `<AiAssistant>` component?

This component should be a very generic textarea input, so for example hardcoding shift + ENTER to fire the `onKeyDown` seems problematic. Somebody could easily need to pass a different `onKeyDown` function that fires regardless of whether that keyboard combination happens.

Seems like `onChange` and `onKeyDown` should be props that spread on the base `textarea`.

I would think usage of this component should be something like:

`<Textarea autoResize={true} {...props} />`

And this component will handle the ref, resizing the input (if the prop is set), etc.

2024-05-20 19:56 UTC, jimniels commented on quadratic-client/src/shared/shadcn/ui/textarea.tsx
> +        {...props}
Or maybe we could just remove the `onKeyDown` handler entirely and let the spread syntax take care of assigning that event handler? 

In that case, the existing `onChange` would handle updates to the component that re-render it's size.

2024-05-20 21:00 UTC, AyushAgrawal-A2 commented on quadratic-client/src/shared/shadcn/ui/textarea.tsx
> +        {...props}
I don't believe it is duplicate code. I'll explain the purpose of event handlers for both the components:

In the `TextArea` component,
 - `onChange` - this triggers auto height adjusting when text-area value changes
 - `onKeyDown` - the submit action i.e. pressing Enter _without_ Shift key, does not trigger the `onChange` event. The value of text-area is emptied and the height needs to be re-adjusted. This requires additional `onKeyDown` event here. Otherwise only having `onChange` was sufficient.

In the `AiAssistant` component,
 - `onChange` - updates the local prompt state. This is controlled input.
 - 'onKeyDown` - triggers submit prompt and clears prompt state, when Enter _without_ Shift key is pressed.

The logic is different in both the components and nothing is being re-implemented. 

I am sorry but I am not able to correlate your feedback to the implementation logic, please correct me if I am wrong here.

2024-05-20 21:00 UTC, AyushAgrawal-A2 commented on quadratic-client/src/app/ui/menus/CodeEditor/AiAssistant.tsx
> +import { Textarea } from '@/shared/shadcn/ui/textarea.js';
Ah.. this project does not require file extensions in imports... this was default on my IDE
p.s.: import will always be `.js`, even for `.tsx` file as it gets transpiled into `.js` eventually

2024-05-21 14:41 UTC, jimniels commented on quadratic-client/src/shared/shadcn/ui/textarea.tsx
> +          `max-h-[${maxHeight || 'none'}]`,
Does this actually work? My understanding is tailwind won't work with dynamic class names. You'd have to turn this into a style attribute instead or something

https://tailwindcss.com/docs/content-configuration#dynamic-class-names

2024-05-21 15:36 UTC, jimniels commented on quadratic-client/src/shared/shadcn/ui/textarea.tsx
> +          `max-h-[${maxHeight || 'none'}]`,
huh, it looks like it does. ok let's keep it.

2024-05-21 16:04 UTC, AyushAgrawal-A2 commented on quadratic-client/src/shared/shadcn/ui/textarea.tsx
> +          `max-h-[${maxHeight || 'none'}]`,
yup, my bad. I have fixed it.

2024-05-21 16:11 UTC, jimniels approved these changes
I added a few additional fixes, tweaks to this, including:

- CMD+Enter submits the textarea, with Enter and Shift+Enter now inserting a line. This aligns the input more broadly with web app textarea inputs (like twitter) as well as our own code editor which uses CMD+Enter to "submit" and run the code while Enter just adds a new line. Added a shortcut to the tooltip to indicate this to the user

![CleanShot 2024-05-21 at 10 10 44@2x](https://github.com/quadratichq/quadratic/assets/1316441/aaeabf9f-a363-4048-a3e6-bc4c1652e596)

- Multi-line user inputs were not displaying as multi-line messages from the user who typed them. Now they do.

![CleanShot 2024-05-21 at 10 00 23@2x](https://github.com/quadratichq/quadratic/assets/1316441/10467601-7ee7-4eeb-9f8d-c98722ef73fe)

- "Send" button aligns to the bottom of the textarea as it expands in height (so does loading indicator)

![CleanShot 2024-05-21 at 09 43 52@2x](https://github.com/quadratichq/quadratic/assets/1316441/868abfbf-f88f-4d27-9f68-dfb526b3b352)

2024-05-21 16:12 UTC, jimniels commented
Will merge this once all tests pass...

2024-05-21 16:39 UTC, merged