Bincode file implementation
quadratichq/quadratic pull request #1350
Opened 2024-05-13 12:18 UTC by davidfig

2024-07-30 10:58 UTC, davidfig commented
Code LGTM . I can't approve since I started this PR. @ddimaria please approve.

2024-07-30 16:24 UTC, davidkircos requested changes
Importing this `.grid` file from the dashboard fails with rust panic

https://fastupload.io/688a351c18be86b3

2024-08-02 19:58 UTC, ddimaria commented on quadratic-core/Cargo.toml
> +name = "generate_blank_current_file"
This automates generating and placing a blank grid file of the current version to be used in 2 places in the repo.

2024-08-02 21:28 UTC, ddimaria commented
> Importing this `.grid` file from the dashboard fails with rust panic
> 
> https://fastupload.io/688a351c18be86b3

This is fixed and related to new upstream code (rows_resize)

2024-08-02 21:52 UTC, ddimaria approved these changes

2024-08-02 21:53 UTC, merged