Docker compose for full infra
quadratichq/quadratic pull request #1385
Opened 2024-05-28 23:59 UTC by ddimaria

2024-07-25 17:08 UTC, ddimaria commented on quadratic-client/package.json
> +    "start:production": "serve build",
@davidkircos this is the only change I'm concerned about.  It's been a while, so I need to research why this was done (json doesn't support comments 😠)

2024-07-25 17:10 UTC, ddimaria commented on quadratic-client/package.json
> +    "start:production": "serve build",
Convo reference: https://quadratichq.slack.com/archives/D05PWQN71AT/p1717107775525889

2024-07-25 20:47 UTC, davidkircos commented on quadratic-api/tsconfig.production.json
> +  "extends": "./tsconfig.json",
is this needed?

2024-07-25 20:50 UTC, davidkircos commented on docker-compose.yml
> +  #     - all
cleanup

2024-07-30 16:13 UTC, davidkircos approved these changes

2024-07-30 16:14 UTC, davidkircos requested changes
Rust tests fail 
![](https://files.slack.com/files-pri/T03KU41MJ86-F07ER1C1EAE/cleanshot_2024-07-30_at_10.13.53_2x.png)

2024-08-01 15:48 UTC, ddimaria commented on docker-compose.yml
> +  #     - all
Done

2024-08-02 22:17 UTC, ddimaria commented on quadratic-api/tsconfig.production.json
> +  "extends": "./tsconfig.json",
It applies values from `tsconfig.json` to `tsconfig.production.json`, though additions in `tsconfig.production.json` override the extended values.

2024-08-05 23:05 UTC, davidkircos approved these changes
rust tests pass, approved!

2024-08-05 23:05 UTC, merged