Build client in docker
quadratichq/quadratic pull request #1402
Opened 2024-05-31 16:14 UTC by ddimaria

2024-06-10 16:59 UTC, jimniels commented on quadratic-client/package.json
> +    "typescript": "^5.4.5",
Why was this added? `typescript` is in the root package.json, so does it need to be here?

2024-06-11 15:29 UTC, ddimaria commented on quadratic-client/package.json
> +    "typescript": "^5.4.5",
I was having build issues without it, it might be the same issue we're getting in the next-connections PR

2024-06-17 20:29 UTC, davidkircos approved these changes

2024-06-17 20:38 UTC, davidkircos requested changes

2024-06-17 20:38 UTC, davidkircos commented on client.Dockerfile
> +RUN echo 'Building wasm...' &&  wasm-pack build --target web --out-dir ../quadratic-client/src/app/quadratic-core --weak-refs
This can also be done form root with `npm run build:wasm:javascript`

2024-06-17 20:38 UTC, davidkircos commented on client.Dockerfile
> +RUN echo 'Exporting TS/Rust types...' && cargo run --bin export_types
`num run build:wasm:types`

2024-06-17 20:38 UTC, davidkircos commented on client.Dockerfile
> +RUN echo 'Building quadratic-rust-client...' && npm run build --workspace=quadratic-rust-client
`npm run build:rust-client`

2024-07-25 17:25 UTC, ddimaria commented on client.Dockerfile
> +RUN echo 'Building wasm...' &&  wasm-pack build --target web --out-dir ../quadratic-client/src/app/quadratic-core --weak-refs
That script changes directories, so can't be used.

2024-07-25 17:26 UTC, ddimaria commented on client.Dockerfile
> +RUN echo 'Exporting TS/Rust types...' && cargo run --bin export_types
That script changes directories, so can't be used.

2024-07-25 17:26 UTC, ddimaria commented on client.Dockerfile
> +RUN echo 'Building quadratic-rust-client...' && npm run build --workspace=quadratic-rust-client
That script changes directories, so can't be used.

2024-07-25 17:44 UTC, davidkircos approved these changes

2024-07-25 18:02 UTC, merged