Encrypt/decrypt typeDetails in API and store encrypted in the DB
quadratichq/quadratic pull request #1432
Opened 2024-06-18 19:03 UTC by ddimaria

2024-06-18 19:15 UTC, ddimaria commented on quadratic-api/src/data/universityDomains.ts
>  // NOTE: this file is automatically generated by quadratic-api/scripts/updateUniversityDomains.js
I re-generated this.

2024-06-18 19:20 UTC, davidkircos commented on quadratic-api/.env.docker
> +ENCRYPTION_KEY=eb4758047f74bdb2603cce75c4370327ca2c3662c4786867659126da8e64dfcc
Can we make the example key, which is obviously not for use in production?

2024-06-18 20:00 UTC, davidkircos commented on quadratic-api/.env.docker
> +ENCRYPTION_KEY=eb4758047f74bdb2603cce75c4370327ca2c3662c4786867659126da8e64dfcc
potentially even add a check to ensure that if `ENVIRONMENT=production` that it isn't using our example key, this will be good for selfhosting

2024-06-18 20:06 UTC, davidkircos commented on quadratic-api/prisma/schema.prisma
> +    typeDetails Bytes // JSON
Update comment 

"InitializationVector:Cyphertext"

2024-06-18 20:20 UTC, davidkircos commented on quadratic-api/src/utils/crypto.ts
> +  const key = getKeyBufferFromEnv();
could probably set once on file load

2024-06-18 20:21 UTC, davidkircos commented on quadratic-api/src/routes/v0/connections.$uuid.GET.ts
> +  const typeDetails = decryptFromEnv(connection.typeDetails?.toString('utf-8') || '');
is a blank string valid here?

2024-06-18 20:23 UTC, davidkircos commented on quadratic-api/src/utils/crypto.ts
> +export const decrypt = (key: Buffer, encryptedText: string): string => {
should this be public or just `decryptFromEnv`?

2024-06-18 20:24 UTC, davidkircos commented on quadratic-api/src/utils/crypto.ts
> +export const encrypt = (key: Buffer, text: string): string => {
don't export?

2024-06-18 20:24 UTC, davidkircos commented on quadratic-api/src/utils/crypto.ts
> +export const decrypt = (key: Buffer, encryptedText: string): string => {
don't export?

2024-06-18 20:25 UTC, davidkircos commented on quadratic-api/src/utils/crypto.ts
> +export const encrypt = (key: Buffer, text: string): string => {
make it clear which functions are for developer use around the app and which ones are internal

2024-06-18 20:26 UTC, davidkircos commented on quadratic-api/src/routes/v0/connections.$uuid.GET.ts
> +  const typeDetails = decryptFromEnv(connection.typeDetails?.toString('utf-8') || '');
Pass to Zod for typing to ensure this is the structure we expect it to be

2024-06-27 17:52 UTC, ddimaria commented on quadratic-api/.env.docker
> +ENCRYPTION_KEY=eb4758047f74bdb2603cce75c4370327ca2c3662c4786867659126da8e64dfcc
I'm adding this to the `env-var.ts` file: 
```typescript
function ensureSampleTokenNotUsedInProduction() {
  if (NODE_ENV !== 'production') return;

  if (process.env.ENCRYPTION_KEY === SAMPLE_ENCRYPTION_KEY) {
    throw new Error(
      `Please set a unique ENCRYPTION_KEY in production. Do not use the sample value.  A new key can be generated with: npm run key:generate`
    );
  }
}
```

2024-07-08 17:44 UTC, davidkircos commented on quadratic-api/src/env-vars.ts
> +const SAMPLE_ENCRYPTION_KEY = 'eb4758047f74bdb2603cce75c4370327ca2c3662c4786867659126da8e64dfcc';
Should we define this as an ENV var?

2024-07-08 17:49 UTC, davidkircos commented on quadratic-api/src/utils/crypto.ts
> +import { ENCRYPTION_KEY } from '../env-vars';
This function looks good. We may consider building in a key rotation system, this may be difficult later. ChatGPT suggests

--- 

Implementing key rotation for an encryption system that is already in production requires a careful approach to ensure data integrity and security. Here’s how you can implement key rotation for the given code:

### Steps for Key Rotation

1. **Introduce a Key Versioning System**:
   - Maintain multiple keys with different versions.
   - The current key version should be stored and accessible.

2. **Encrypt New Data with the Latest Key**:
   - Use the latest key for encrypting any new data.

3. **Decrypt Existing Data with the Appropriate Key**:
   - Identify the key used to encrypt the data (e.g., by storing the key version with the encrypted data) and use the appropriate key for decryption.

4. **Re-encrypt Old Data with the New Key**:
   - Gradually re-encrypt existing data with the new key to ensure a smooth transition.

### Implementation

#### 1. Key Management

Create a key management file (e.g., `keyManager.js`) to handle multiple keys and their versions.

```javascript
import crypto from 'crypto';
import { ENCRYPTION_KEYS } from '../env-vars'; // Assumes ENCRYPTION_KEYS is a JSON string with versioned keys

const keys = JSON.parse(ENCRYPTION_KEYS);

// Get the latest key version
const getCurrentKey = () => {
  const latestVersion = Math.max(...Object.keys(keys).map(Number));
  return { key: Buffer.from(keys[latestVersion], 'hex'), version: latestVersion };
};

// Get a specific key version
const getKey = (version) => {
  if (!keys[version]) {
    throw new Error(`Key version ${version} not found`);
  }
  return Buffer.from(keys[version], 'hex');
};

export { getCurrentKey, getKey };
```

#### 2. Encrypt with Key Versioning

Update the encryption functions to include the key version in the output.

```javascript
import crypto from 'crypto';
import { getCurrentKey, getKey } from './keyManager';

const algorithm = 'aes-256-cbc';

const encrypt = (key, text) => {
  const iv = crypto.randomBytes(16);
  const cipher = crypto.createCipheriv(algorithm, key, iv);
  const encrypted = Buffer.concat([cipher.update(text), cipher.final()]);

  return iv.toString('hex') + ':' + encrypted.toString('hex');
};

export const encryptWithKeyRotation = (text) => {
  const { key, version } = getCurrentKey();
  const encrypted = encrypt(key, text);
  return `${version}:${encrypted}`;
};
```

#### 3. Decrypt with Key Versioning

Update the decryption functions to handle the key version.

```javascript
import crypto from 'crypto';
import { getKey } from './keyManager';

const algorithm = 'aes-256-cbc';

const decrypt = (key, encryptedText) => {
  const [ivHex, encryptedHex] = encryptedText.split(':');

  if (!ivHex || !encryptedHex) {
    throw new Error('Invalid encrypted text format');
  }

  const iv = Buffer.from(ivHex, 'hex');
  const encrypted = Buffer.from(encryptedHex, 'hex');
  const decipher = crypto.createDecipheriv(algorithm, key, iv);
  const decrypted = Buffer.concat([decipher.update(encrypted), decipher.final()]);

  return decrypted.toString();
};

export const decryptWithKeyRotation = (encryptedText) => {
  const [version, data] = encryptedText.split(':', 2);
  const key = getKey(version);
  return decrypt(key, data);
};
```

#### 4. Re-encryption Process

Create a script to re-encrypt existing data with the new key. This script should be run as a one-time migration or periodically until all data is re-encrypted.

```javascript
import { decryptWithKeyRotation, encryptWithKeyRotation } from './encryption';
import { getCurrentKey } from './keyManager';
import { getAllEncryptedData, updateEncryptedData } from './database'; // Pseudocode for database operations

const reencryptData = async () => {
  const { version: currentVersion } = getCurrentKey();
  const dataEntries = await getAllEncryptedData();

  for (const entry of dataEntries) {
    const { id, encryptedText } = entry;
    const [version] = encryptedText.split(':', 1);

    if (version < currentVersion) {
      const decryptedText = decryptWithKeyRotation(encryptedText);
      const newEncryptedText = encryptWithKeyRotation(decryptedText);
      await updateEncryptedData(id, newEncryptedText);
    }
  }
};

reencryptData().catch(console.error);
```

### Summary

This implementation covers the following:

- Key management with versioning.
- Encryption that includes the key version.
- Decryption that retrieves and uses the appropriate key version.
- A re-encryption script to update old encrypted data with the new key.

Ensure to test this implementation thoroughly in a staging environment before deploying to production.

2024-07-08 17:49 UTC, davidkircos requested changes
Left a couple of comments, no specific changes just looking for your response. Also waiting on resolving merge conflicts.

2024-07-08 22:29 UTC, ddimaria commented on quadratic-api/src/utils/crypto.ts
> +export const encrypt = (key: Buffer, text: string): string => {
I need to change these back to exporting for tests to work.

2024-07-08 22:31 UTC, ddimaria commented on quadratic-api/src/env-vars.ts
> +const SAMPLE_ENCRYPTION_KEY = 'eb4758047f74bdb2603cce75c4370327ca2c3662c4786867659126da8e64dfcc';
I don't think so.  This is what we used to match against the env var `ENCRYPTION_KEY`.  The sole purpose of this var is to catch accidental use of publicly used keys in production, and has no use for developers.

2024-07-08 22:36 UTC, ddimaria commented on quadratic-api/src/utils/crypto.ts
> +import { ENCRYPTION_KEY } from '../env-vars';
I think this is a good idea, but probably overkill for this stage.  This has been in PR for 3 weeks already and keeping this PR up to date is cumbersome.  Maybe we can merge and just update with a more sophisticated system before launch?

2024-07-08 23:40 UTC, ddimaria commented on quadratic-api/src/routes/v0/connections.$uuid.GET.ts
> +  const typeDetails = decryptFromEnv(connection.typeDetails?.toString('utf-8') || '');
Blank string option removed.

2024-07-09 00:37 UTC, davidkircos approved these changes

2024-07-09 00:40 UTC, davidkircos commented on quadratic-api/src/utils/crypto.ts
> +export const decrypt = (key: Buffer, encryptedText: string): string => {
These are only used in this file right? 

rename `decryptFromEnv` `decryptUsingEnv` and `encryptUsingEnv`?

2024-07-09 00:40 UTC, merged