poc: import formulas when importing xlsx file
quadratichq/quadratic pull request #1441
Opened 2024-06-20 05:03 UTC by AyushAgrawal-A2

part of #1435 

Changes:
- Importing formulas work, and results are correct for supported functions.

2024-06-24 23:04 UTC, davidkircos commented
We should add all Excel formulas to the Rust Formulas parser so that ones that people attempt to use, but are not implemented yet can trigger a mixpanel event and we can prioritize implementation.

2024-06-25 11:36 UTC, AyushAgrawal-A2 commented
> We should add all Excel formulas to the Rust Formulas parser so that ones that people attempt to use, but are not implemented yet can trigger a mixpanel event and we can prioritize implementation.

@davidkircos 
Changes:
   - Added excel's function list and check for unimplemented functions
   - Added mixpanel tracking for unimplemented error

![image](https://github.com/quadratichq/quadratic/assets/54364088/5a78732f-85e3-4134-a59d-83cc417e6b5a)

Currently, tracking will trigger only when user runs a formula with a valid excel function that is not implemented yet. Importing xlsx file is a server transaction and does not trigger mixpanel tracking. Is this ok ?

2024-06-28 13:02 UTC, ddimaria commented on quadratic-core/src/controller/execution/execute_operation/execute_code.rs
> +                unreachable!("Only a user/server transaction should have a ComputeCode");
I never liked all of this `unreachable` code.  Ideally, all of these failable functions would return results, but that's a lot of restructuring to do.  Could you try using `dbgjs!` instead and avoid the computation in the error case?

2024-06-28 13:04 UTC, ddimaria commented on quadratic-client/src/app/gridGL/cells/CellsArray.ts
> +          console.warn('[CellsArray] Error parsing codeCell.evaluation_result', error);
If this is an error case, convert to `console.error` so that Sentry can pick up this error.

2024-06-28 13:10 UTC, ddimaria commented on quadratic-core/src/controller/operations/import.rs
> +            let mut formula_compute_ops = vec![] as Vec<Operation>;
You should be able to drop the `as Vec<Operation>` as this should be inferenced by the push on line 222.

2024-06-28 14:57 UTC, AyushAgrawal-A2 commented on quadratic-core/src/controller/execution/execute_operation/execute_code.rs
> +                unreachable!("Only a user/server transaction should have a ComputeCode");
@ddimaria 
Done

2024-06-28 14:57 UTC, AyushAgrawal-A2 commented on quadratic-client/src/app/gridGL/cells/CellsArray.ts
> +          console.warn('[CellsArray] Error parsing codeCell.evaluation_result', error);
@ddimaria 
Done

2024-06-28 14:57 UTC, AyushAgrawal-A2 commented on quadratic-core/src/controller/operations/import.rs
> +            let mut formula_compute_ops = vec![] as Vec<Operation>;
@ddimaria 
Done

2024-06-28 15:54 UTC, ddimaria commented
Good PR @AyushAgrawal-A2 !  Can you either add all supported functions to the `imports_a_simple_excel_file()` test located at `src/controller/user_actions/import.rs` or create a new test there for functions?  I think I just generated the initial Excel file from the free online version.

2024-06-28 23:11 UTC, AyushAgrawal-A2 commented
> Good PR @AyushAgrawal-A2 ! Can you either add all supported functions to the `imports_a_simple_excel_file()` test located at `src/controller/user_actions/import.rs` or create a new test there for functions? I think I just generated the initial Excel file from the free online version.

@ddimaria 
Done

2024-07-01 22:34 UTC, HactarCE requested changes

2024-07-01 22:34 UTC, HactarCE commented on quadratic-core/src/controller/operations/import.rs
> +        let re = Regex::new(r"(?:^|[^A-Za-z\d])(?:_xlfn|_xludf)\.").unwrap();
I think this consumes the last character before the `_xlfn.`/`_xludf.`. For example, running the replacement on `1+_xlfn.SUM(A1:10)` results in `1_xlfn.SUM(A1:10)`. Would it be ok to just use `r"(_xlfn|_xludf)\."`?

This also eats any string literal containing these characters, which is admittedly a pathological input but nonetheless may be a reason to properly parse & reserialize formulas when doing the replacement.

2024-07-01 22:34 UTC, HactarCE commented on quadratic-core/src/controller/operations/import.rs
>          let error =
This error is always used with an `XlsxError`, so we can factor the `.to_string()` into here and then simplify the call sites:

```rs
let error = |e: XlsxError| anyhow!("Error parsing Excel file {file_name}: {e}");

// ... then at call sites:
.map_err(error)
```
String formatting implicitly calls `.to_string()`.

2024-07-01 22:34 UTC, HactarCE commented on quadratic-core/src/controller/operations/import.rs
> +                        let code = re.replace_all(cell, "").into_owned();
Add a comment here explaining what this `.replace_all()` is for, and maybe move the regex closer to the call site. It took me a minute to figure it out because the regex is defined ~65 lines earlier.

You could even put it in a `lazy_static!` _right_ above this line, so that it's only executed once for the whole program but it's still close to where it's used. If that makes the loop body too big, pull out the whole string replacement into a separate function.

2024-07-01 22:34 UTC, HactarCE commented on quadratic-core/src/controller/operations/import.rs
> +                        });
@ddimaria Do you know if this will work well with formula dependencies? Will it run some code cells multiple times or use outdated results or do any other silly things?

Actually, is this even necessary if we `rerun_all_code_cells_operations()` up in `import_excel()`?

2024-07-01 22:34 UTC, HactarCE commented on quadratic-core/src/controller/user_actions/import.rs
> +    const EXCEL_FUNCTIONS_FILE: &str =
Why not [`include_str!()`](https://doc.rust-lang.org/std/macro.include_str.html) and [`include_bytes!()`](https://doc.rust-lang.org/std/macro.include_bytes.html)?

2024-07-01 22:34 UTC, HactarCE commented on quadratic-core/src/controller/user_actions/import.rs
> +        file.read_exact(&mut buffer).expect("buffer overflow");
If not [`include_str!()`](https://doc.rust-lang.org/std/macro.include_str.html), why not [`std::fs::read()`](https://doc.rust-lang.org/std/fs/fn.read.html)?

2024-07-01 23:09 UTC, AyushAgrawal-A2 commented on quadratic-core/src/controller/operations/import.rs
> +        let re = Regex::new(r"(?:^|[^A-Za-z\d])(?:_xlfn|_xludf)\.").unwrap();
@HactarCE 
I should have used positive look behind `r"(?<=^|[^A-Za-z\d])(?:_xlfn|_xludf)"` to assert a non word character before this prefix. This will not consume other characters.

In first iteration I did not clean the input, instead after lexar tokenization... I used just remove the prefix `_xlfn. / _xludf.` inside `lookup_function`. In this case prefix will always be at the start of string. This approach did not have the issue of removing characters from strings or other places.

I thought it is bad to save a dirty input so switched to cleaning it at import.

2024-07-01 23:55 UTC, AyushAgrawal-A2 commented on quadratic-core/src/controller/user_actions/import.rs
> +        file.read_exact(&mut buffer).expect("buffer overflow");
I copy-pasted file reading code from other functions in the same file.
switched all to `std::fs::read`

2024-07-01 23:57 UTC, AyushAgrawal-A2 commented on quadratic-core/src/controller/operations/import.rs
> +        let re = Regex::new(r"(?:^|[^A-Za-z\d])(?:_xlfn|_xludf)\.").unwrap();
look-ahead is not supported, switched back to earlier implementation. now storing code string as it is.

2024-07-02 21:49 UTC, HactarCE approved these changes
Thanks for the changes!

2024-07-08 19:52 UTC, davidkircos commented
Looks great to me! Going to merge this branch. I repurposed this Issue to track our overall Excel File import support https://github.com/quadratichq/quadratic/issues/1154

2024-07-08 20:02 UTC, merged