fix: expanded formula editor code suggestions not working
quadratichq/quadratic pull request #1511
Opened 2024-07-03 12:38 UTC by AyushAgrawal-A2

closes #1503

2024-07-20 12:42 UTC, davidfig commented
Please resolve conflicts

2024-07-20 15:45 UTC, AyushAgrawal-A2 commented
> Please resolve conflicts

@davidfig 
done

2024-07-22 21:23 UTC, davidkircos commented
@AyushAgrawal-A2 formulas syntax highlighting and cell highlighting also don't work in the expanded editor. Could you also fix those issues in this PR?

2024-07-22 22:35 UTC, AyushAgrawal-A2 commented
> @AyushAgrawal-A2 formulas syntax highlighting and cell highlighting also don't work in the expanded editor. Could you also fix those issues in this PR?

@davidfig 
done

2024-07-24 03:59 UTC, davidkircos requested changes

2024-07-24 03:59 UTC, davidkircos commented on quadratic-rust-shared/src/sql/mysql_connection.rs
> +        assert!(!over_the_limit);
should this be in this branch?

2024-07-24 03:59 UTC, davidkircos commented on quadratic-client/src/dashboard/components/CustomRadixIcons.tsx
> +          clipRule="evenodd"
are these intended changes?

2024-07-24 03:59 UTC, davidkircos commented on docker/localstack/scripts/init-aws.sh
is this an intended change?

2024-07-24 04:04 UTC, AyushAgrawal-A2 commented on quadratic-rust-shared/src/sql/mysql_connection.rs
> +        assert!(!over_the_limit);
yup `lint:clippy` gives warning for this
already merge in qa branch in PR #1450

2024-07-24 04:04 UTC, AyushAgrawal-A2 commented on quadratic-client/src/dashboard/components/CustomRadixIcons.tsx
> +          clipRule="evenodd"
yup, this throws error in chrome dev console
already merge in qa branch in PR #1450

2024-07-24 04:05 UTC, AyushAgrawal-A2 commented on docker/localstack/scripts/init-aws.sh
yup, this matches the name used in docker-compose.yml
already merge in qa branch in PR #1450

2024-07-24 04:06 UTC, AyushAgrawal-A2 commented
On merging `qa` into this branch the above diffs are gone

2024-07-24 18:03 UTC, davidkircos approved these changes

2024-07-24 18:03 UTC, merged