Improvements to ensureVisible when moving/selecting cells
quadratichq/quadratic pull request #1553
Opened 2024-07-15 22:14 UTC by davidfig

- [x] Shift+click will move viewport to the edge of the selection instead of the cursor
- [x] Shift+arrow will move viewport to the edge of the selection instead of cursor

Fixes #1532

2024-07-19 19:17 UTC, ddimaria commented on quadratic-client/src/app/grid/sheet/SheetCursor.ts
> +      ensureVisible?: boolean | Coordinate;
I don't know enough context here, but this seems like it should be a separate variable (or maybe a variable rename)?

2024-07-19 19:19 UTC, ddimaria commented
Code looks good (I have one comment).  I'll let @davidkircos approve once he validates this in the UI.

2024-07-22 22:03 UTC, davidkircos requested changes
I am not sure what all the changes in their PR do. Can you give a video example?

This does seem to fix the initial issue.

2024-07-23 10:40 UTC, davidfig commented on quadratic-client/src/app/grid/sheet/SheetCursor.ts
> +      ensureVisible?: boolean | Coordinate;
This provides another option for ensureVisible. The default is to either do nothing (false) or move to the current cursor position (true). The Coordinate is when you want to move to a different cursor position. For example, when selecting a range, you want to move the viewport to the corner of the range, not the cursor position (which is where the range starts).

2024-07-23 10:51 UTC, davidfig commented
This changes when the viewport moves mostly during keyboard selection. Originally, it used the starting cursorPosition. This changes it to use the ending cursor position for selections, like shift + arrow or shift + cmd + arrow.

Old behavior: 

https://github.com/user-attachments/assets/5b3fa9a1-dcc8-4767-aef6-e3b2475e4458

New Behavior:

https://github.com/user-attachments/assets/5a0f517d-4377-48e1-95fe-849da5548a2b

2024-07-24 04:11 UTC, davidkircos approved these changes

2024-07-24 04:11 UTC, merged