Add `INDEX` function
quadratichq/quadratic pull request #1555
Opened 2024-07-16 16:28 UTC by HactarCE

Adds `INDEX` function and refactors/fixes `only_parse`

2024-07-19 18:21 UTC, ddimaria commented on quadratic-core/src/formulas/ast.rs
> +                if only_parse {
Not for this PR, but it would be nice to separate out the parsing and evaluation functionality to remove this `only_parse` arg passing.

2024-07-19 18:24 UTC, ddimaria commented on quadratic-core/src/formulas/ctx.rs
> +                let sheet_pos1 = self.resolve_ref(start, span)?.inner;
Nit: there could be a more descriptive var name here:  e.g. `sheet_pos1` => `sheet_pos_start`

2024-07-19 18:26 UTC, ddimaria commented on quadratic-core/src/formulas/ctx.rs
> +                // TODO: record array dependency instead of many individual cell dependencies
Is this TODO for a later date?

2024-07-19 19:03 UTC, ddimaria commented on quadratic-core/src/formulas/functions/lookup.rs
> +    fn test_index() {
Great tests 💯

2024-07-19 19:09 UTC, ddimaria commented on quadratic-core/src/position.rs
> +    pub fn pos(&self) -> Pos {
We already have this code in this file: 

```rust
impl From<SheetPos> for Pos {
    fn from(sheet_pos: SheetPos) -> Self {
        Pos {
            x: sheet_pos.x,
            y: sheet_pos.y,
        }
    }
}
```

2024-07-19 19:14 UTC, ddimaria commented
Looks great @HactarCE!  I left a few comments, but nothing really critical.  CI is failing at several checks.  Let me know once CI is successful b/c I just need to confirm that test coverage didn't go down.

2024-07-19 19:21 UTC, HactarCE commented on quadratic-core/src/formulas/ast.rs
> +                if only_parse {
How much is "parsing" supposed to evaluate? Just base syntax, number of arguments, types of arguments...?

2024-07-19 19:29 UTC, HactarCE commented on quadratic-core/src/formulas/ctx.rs
> +                // TODO: record array dependency instead of many individual cell dependencies
Yep. This has been here for a while and is wayy outside the scope of this PR. I think it would involve file schema changes.

2024-07-19 19:30 UTC, HactarCE commented on quadratic-core/src/position.rs
> +    pub fn pos(&self) -> Pos {
Whoops! Thanks

2024-08-01 15:42 UTC, ddimaria approved these changes

2024-08-05 23:07 UTC, davidkircos requested changes
preview branch can't create new blank files 
![CleanShot 2024-08-05 at 17 07 27@2x](https://github.com/user-attachments/assets/24731551-d218-4ebc-8315-f74420928e19)

2024-08-06 16:49 UTC, HactarCE commented
Locally I can make new files, and I can't think of any change I made here that could cause an issue with making a new blank file.

2024-08-06 18:22 UTC, davidkircos approved these changes

2024-08-06 18:22 UTC, merged