feat: tweaked prompt for ai returning sql queries
quadratichq/quadratic pull request #1567
Opened 2024-07-18 20:14 UTC by jimniels

Today, the AI returns a sql query that doesn't have the right quoting. This means the query might not run.

For example, it gave me this:

```sql
SELECT 
    Team.name AS team_name, 
    COUNT(UserTeamRole.user_id) AS user_count 
FROM 
    public.Team
JOIN 
    public.UserTeamRole 
ON 
    Team.id = UserTeamRole.team_id
GROUP BY 
    Team.name
ORDER BY 
    user_count DESC;
```

Which I had to tweak to this, to get it to run:

```sql
SELECT 
    "Team".name AS team_name, 
    COUNT("UserTeamRole".user_id) AS user_count 
FROM 
    public."Team"
JOIN 
    public."UserTeamRole" 
ON 
    "Team".id = "UserTeamRole".team_id
GROUP BY 
    "Team".name
ORDER BY 
    user_count DESC;
```

The idea is to tell the AI to return queries like that by default following the same logic we used in our code base for inserting a query: Postgres queries do `"schema"."Table"` and MySQL queries do `` `schema`.`Table` ``

2024-07-18 20:15 UTC, jimniels commented on quadratic-client/src/app/ui/menus/CodeEditor/AiAssistant.tsx
> +      ].join('\n')
Idk if this is the best way to write this prompt. It'll do it to everything, and maybe you don't always want that? I'm no SQL pro.

Example:

![CleanShot 2024-07-18 at 14 14 54@2x](https://github.com/user-attachments/assets/8991b1ca-625c-402c-a726-cc495e1b33ec)

2024-07-22 18:22 UTC, davidkircos requested changes
yeah I don't think we want it to do this for all field names

2024-09-04 22:16 UTC, davidkircos commented
I am running into this issue all the time, resurrecting this change

2024-09-13 11:39 UTC, closed without merging

2024-09-13 11:39 UTC, AyushAgrawal-A2 commented
added in https://github.com/quadratichq/quadratic/pull/1864