perf: improve autocomplete performance
quadratichq/quadratic pull request #1595
Opened 2024-07-23 16:28 UTC by AyushAgrawal-A2

for #1556 
This PR is meant for trial and discussion, may not merge

Problems causing #1556 
All workers are busy due to large number of operations. After waiting for some time app becomes responsive again. To see this visually, create a cell with some formatting and sheet fill. Drag it, via autocomplete, to a large selection. Water falling format updates can be seen progressing.

This is happening because each formatting update for every cell is applied in a separate operation. This leads to:
- Large number of inter worker message which take a lot of time.
- Sending individual cell update for each operation, cause unnecessary render updates.
- Use of `transaction.reverse_operations.insert(0, ...` which is O(n^2) for n operations.

In this PR, I am trying to batch client updates. Sending update for the entire affected `sheet_rect` is faster than filter and sending only changes for each individual cell.

Current performance in this PR is a lot faster than before but still slower than google sheets / excel web. More optimisations can be done.
Also this can improve performance of copy paste as well. Not implemented in this PR.

2024-07-24 11:03 UTC, davidfig commented
Awesome. This was definitely on my list as well. I thought of two approaches for this problem: (1) your approach to batch the client calls to avoid rerendering hashes multiple times; and (2) rewriting the Operation::SetCellValues to be more efficient and accept something other than CellValues. The problem with CellValues is that it has to be a rectangle, and autocomplete is always a rectangle with a corner removed.

What are your thoughts on continued improvement?

2024-07-24 13:37 UTC, AyushAgrawal-A2 commented
@davidfig 
I am already trying to figure out -
- Refactoring to Operation::SetCellFormatsSelection 
- How to do batch client update for multiplayer, currently only operations are sent to multiplayer.

Current bottleneck is in `finalize_transaction` step, after sending batch client update. Size of reverse_operations vector is huge. Processing it and sending all those transactions is taking >90% of time currently.

hash boundaries bug is fixed in #1526

2024-07-24 13:50 UTC, davidfig commented
Cool. Great on the hash boundaries bug. 

I'm not sure if we need to batch the client updates for multiplayer. We've been handling multiplayer via transactions, and I'm reluctant to change that.

Ideally, we should reduce the number of the operations.

2024-07-24 14:02 UTC, AyushAgrawal-A2 commented
@davidfig 
I am also reluctant to change multiplayer, a lot of code I don't understand yet.
But I don't know how else to solve water falling client update and large number of worker messages for multiplayer.

Reducing operations is priority, I am trying to do that too but even if there are a ton of operations multiplayer should be able to batch update same as host client is doing.

2024-07-24 14:04 UTC, davidfig commented
If the batching works at the level of the transaction, then mp should work fine. It runs the ops via shared transactions.

2024-07-24 21:23 UTC, AyushAgrawal-A2 commented
@davidfig 
alot faster now :man_dancing:

2024-07-24 22:39 UTC, davidkircos commented
Yeah, wow, this is way faster! Is this PR ready for review?

2024-07-24 22:55 UTC, AyushAgrawal-A2 commented
@davidkircos 
I would like to add some test if we are to merge this PR

Also, I am not able to figure out how to batch client update for multiplayer. Water falling is still present for MP. Can be done in another PR.

Otherwise, ready for user testing

2024-07-25 04:36 UTC, AyushAgrawal-A2 commented
@davidfig 
switch to `SetCellFormatsSelection`
faster than excel web now, I am satisfied with the performance

2024-07-25 12:06 UTC, davidfig commented
Awesome. Can you also increase test coverage? Thanks!

2024-07-25 12:09 UTC, AyushAgrawal-A2 commented
> Awesome. Can you also increase test coverage? Thanks!

Yup, on it

2024-07-25 15:08 UTC, AyushAgrawal-A2 commented
I wanted to add `expect_js_call_count` in test for `batch_client_update` but this required adding `#[parallel]` macro to all tests.
I have already done that in #1526. Can be done after merging it.

2024-07-25 15:26 UTC, davidfig commented
Can you add the batch_client_update_rect to receive_multiplayer#received_transction? Wouldn't that add this functionality to mp, or is there more that needs to happen?

2024-07-25 15:37 UTC, davidfig requested changes

2024-07-25 15:37 UTC, davidfig commented on quadratic-core/src/controller/execution/execute_operation/mod.rs
> +                && transaction.batch_client_update_rect.is_none()
Why are you checking the batch here?

2024-07-25 15:39 UTC, AyushAgrawal-A2 commented on quadratic-core/src/controller/execution/execute_operation/mod.rs
> +                && transaction.batch_client_update_rect.is_none()
to solve too many worker messages for transactions having large number of operations
worker message are very slow

2024-07-25 15:43 UTC, davidfig commented
Cool. If you can make it dynamic, then mp should just work. We can be naive and use a Bounds struct that allows you to increase its size based on what the ops are doing.

2024-07-25 15:43 UTC, AyushAgrawal-A2 commented
I hate this bot :angry: 
![image](https://github.com/user-attachments/assets/00dac136-2a54-43d6-a023-df897913918e)

![image](https://github.com/user-attachments/assets/6637113f-abb9-4f05-86d1-9e139e42adbc)

2024-07-25 15:47 UTC, AyushAgrawal-A2 commented
> Cool. If you can make it dynamic, then mp should just work. We can be naive and use a Bounds struct that allows you to increase its size based on what the ops are doing.

yup, I figured this much. we still need a way to tell mp than it needs to batch operations and not send individual updated.
maybe based on operations vector size, I am sure now
current bottleneck is `send_transactions` which should be solve by #1607

2024-07-25 15:48 UTC, davidfig commented
> we still need a way to tell mp than it needs to batch operations and not send individual updated

If it's dynamically updated in a more complicated Batch struct, then we'll know exactly what needs to be sent to the client based on the execute operation (which should update the Batch struct as it executes).

2024-07-25 15:54 UTC, AyushAgrawal-A2 commented
> > we still need a way to tell mp than it needs to batch operations and not send individual updated
> 
> If it's dynamically updated in a more complicated Batch struct, then we'll know exactly what needs to be sent to the client based on the execute operation (which should update the Batch struct as it executes).

I disagree actually, having fine grained updates was the biggest issue that this PR solve. This will again lead to multiple re-renders and a ton of worker messages depending on the complexity of Batch struct.

My idea behind batch update is to not figure out finer updates, but instead to send a larger rect re-render to avoid 
- multiple rerenders of  same hash 
- number of worker messages

Worker messages is the slowest step here, which I am trying to optimise

2024-07-25 15:58 UTC, davidfig commented
Hmm... I'm not sure I follow. My suggestion is to create a Batch struct that tracks all changes made by operations. Then in finalize_transaction, we use the Batch struct to send the necessary messages.

To avoid too many messages, you can combine the rects before sending the messages. For example, you collect a set of cell hashes that have changed based on the rects, then you only send those cell hashes (so each cell hash is only sent once).

You end up with the correct number of messages this way without having to define the rect before the transaction is executed. Does that make sense?

2024-07-25 17:51 UTC, AyushAgrawal-A2 commented
@davidfig 
Batch update part is not doing much now after moving to 'SetCellFormatsSelection'. Earlier each cell had 10 operations for format update. Now we have just one operation for all format updates for the entire rect.
I should have done this before playing with other code.

As we have just ~2 operations now re-renders and worker messages are almost same as what we would achieve with a Batch struct.

I have disable it and push it here. Please try it on Vercel preview. It is pretty fast. I tried autocomplete for a very large rect `1x4` to `10000 x 8`. Add lot of different formatting in source rect to stress the operation. It looks OK to me.

I think we can remove & postpone Batch update logic.
I get what you are saying but I am not able to think of a scenario which I can implement and compare practically.

2024-07-25 17:53 UTC, davidfig commented
Sounds good. We'll likely revisit the batching down the road.

2024-07-25 17:56 UTC, AyushAgrawal-A2 commented
> Sounds good. We'll likely revisit the batching down the road.

Great... Thanks for working this out with me. This PR was meant to do exactly this :smiley: 

Also removing batch_update logic might satisfy the insatiable codecov bot :stuck_out_tongue_closed_eyes:

2024-08-06 00:57 UTC, merged