Serialize and compress transactions
quadratichq/quadratic pull request #1607
Opened 2024-07-24 23:21 UTC by ddimaria

2024-07-30 19:01 UTC, HactarCE commented on quadratic-core/src/controller/execution/receive_multiplayer.rs
> +                .position(|t| t.sequence_num.unwrap_or(0) < sequence_num)
Can you add a doc comment to `sequence_num` explaining why it might be `None`? Glancing at this code, I don't know if `.unwrap_or(0)` is correct.

2024-07-30 19:04 UTC, HactarCE commented on quadratic-core/src/controller/transaction.rs
> +pub static CURRENT_VERSION: &str = "1.0";
Will this need to be incremented any time we add a new kind of operation or new formatting option?

2024-07-30 19:15 UTC, HactarCE reviewed
Sorry, I forgot to do the official "start a review" thing so my first few comments landed outside.

Besides a few small things, the Rust side looks good to me!

2024-07-30 19:15 UTC, HactarCE commented on quadratic-files/src/truncate.rs
> +        return Err(FilesError::Unknown("Could not parse key {key}".into()));
Needs `format!(...).into()`

2024-07-30 19:15 UTC, HactarCE commented on quadratic-rust-shared/src/pubsub/redis_streams.rs
> +type Message = (String, Vec<u8>);
Can you add a doc comment that says what each of these is? And/or make it a `struct` with named fields.

2024-08-02 22:01 UTC, ddimaria commented on quadratic-files/src/truncate.rs
> +        return Err(FilesError::Unknown("Could not parse key {key}".into()));
Nice catch ❤️ , this is done.

2024-08-02 22:03 UTC, ddimaria commented on quadratic-rust-shared/src/pubsub/redis_streams.rs
> +type Message = (String, Vec<u8>);
I added the following: 

> // A message consists of a key (String) and a value (Bytes).

2024-08-02 22:08 UTC, ddimaria commented on quadratic-core/src/controller/transaction.rs
> +pub static CURRENT_VERSION: &str = "1.0";
This is untested, but I imagine the version will bump anytime there is a structural (minor) or breaking change (major, i.e. when it's not backwards compatible).  Changing the compression or serialization format would cause a increase in the major version and the necessity to add in some pattern matching for handling the different versions (TBD when the version bumps).  Additions to the structure will likely bump the minor version (tests should indicate this need) and not require any additional work.

2024-08-02 22:14 UTC, ddimaria commented on quadratic-core/src/controller/execution/receive_multiplayer.rs
> +                .position(|t| t.sequence_num.unwrap_or(0) < sequence_num)
After reviewing more of the quadratic-core code, I believe you're correct Andrew.  I updated this value to be:

```rust
self.transactions.out_of_order_transactions.len()
```

2024-08-02 22:15 UTC, ddimaria commented on quadratic-core/src/controller/execution/receive_multiplayer.rs
> +                .position(|t| t.sequence_num.unwrap_or(0) < sequence_num)
@davidfig can you confirm the above?

2024-08-06 19:18 UTC, davidfig approved these changes
Approved with a couple of nonblocking comments.

2024-08-06 19:18 UTC, davidfig commented on quadratic-client/vite.config.js.timestamp-1722017521018-562d6b4f12d52.mjs
What's this?

2024-08-06 19:18 UTC, davidfig commented on quadratic-core/src/controller/execution/receive_multiplayer.rs
> +            }
Can we get test coverage on these? You can use the debug version of js.rs. If the ops are large, then use the hash_test() instead of the actual string.

2024-08-06 22:11 UTC, davidkircos requested changes
This creates invalid transactions and breaks the sheet. May be because of other code merged from `qa` into this branch...
https://github.com/user-attachments/assets/4d27e9b0-b5fa-4b2c-bac6-ad417b32370b

2024-08-07 15:19 UTC, ddimaria commented on quadratic-client/vite.config.js.timestamp-1722017521018-562d6b4f12d52.mjs
I have no clue.  It seems to be an auto-generated file from Vite: https://github.com/vitejs/vite/issues/13267

I'll delete it.

2024-08-07 15:24 UTC, ddimaria commented on quadratic-client/vite.config.js.timestamp-1722017521018-562d6b4f12d52.mjs
Deleted

2024-08-07 15:30 UTC, ddimaria commented on quadratic-core/src/controller/execution/receive_multiplayer.rs
> +            }
The tests for compression and serialization are in the compression.rs file.  The only reason why there is no coverage for lines 243 - 246 is because this function does not return a result (it should since there are multiple fail-able situations).  Adding result support requires a bit of a rewrite since much of core isn't returning results.  Did you want me to implement a returned result for this function?

2024-08-07 23:36 UTC, ddimaria commented
> This creates invalid transactions and breaks the sheet. May be because of other code merged from `qa` into this branch... https://github.com/user-attachments/assets/4d27e9b0-b5fa-4b2c-bac6-ad417b32370b

I can duplicate this.  You have to refresh before the files service processes the transactions.

2024-08-08 00:48 UTC, ddimaria commented on quadratic-client/src/app/web-workers/quadraticCore/worker/core.ts
> +          this.gridController.multiplayerTransaction(data.id, data.sequence_num, data.operations);
@davidfig it's more performant to send the transaction individually.  Do you see a problem with this?

2024-08-08 00:49 UTC, ddimaria commented
> This creates invalid transactions and breaks the sheet. May be because of other code merged from `qa` into this branch... https://github.com/user-attachments/assets/4d27e9b0-b5fa-4b2c-bac6-ad417b32370b

@davidkircos This is fixed, can you verify once the build is done?

2024-08-08 14:41 UTC, ddimaria commented on quadratic-client/src/app/web-workers/quadraticCore/worker/core.ts
> +          this.gridController.multiplayerTransaction(data.id, data.sequence_num, data.operations);
We had a slack conversation.  We're going to keep the individual transaction sending for 5 - 7 days after deploying this branch, then send the full payload as binary from multiplayer and just forward to core (more optimal than the current approach).

2024-08-09 22:18 UTC, davidkircos requested changes
Can not download .grid file 
![CleanShot 2024-08-09 at 16 17 36@2x](https://github.com/user-attachments/assets/46957263-406f-4e11-a334-068d29fdf568)

2024-08-09 22:23 UTC, davidkircos commented
tested a 3.3mb Parquet file
On this branch is 8mb, previously it was 48mb! This is sweet.

2024-08-10 09:28 UTC, AyushAgrawal-A2 reviewed
Importing 0.5M file fails, this works in main and qa.
>=1M file fails on main and qa.
Files link: https://github.com/datablist/sample-csv-files

![image](https://github.com/user-attachments/assets/fbb23de8-77e0-4656-af99-1cf75e0eb8d0)

2024-08-13 21:37 UTC, ddimaria commented
> Can not download .grid file ![CleanShot 2024-08-09 at 16 17 36@2x](https://private-user-images.githubusercontent.com/3479421/356766004-46957263-406f-4e11-a334-068d29fdf568.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjM1ODQyNjksIm5iZiI6MTcyMzU4Mzk2OSwicGF0aCI6Ii8zNDc5NDIxLzM1Njc2NjAwNC00Njk1NzI2My00MDZmLTRlMTEtYTMzNC0wNjhkMjlmZGY1NjgucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDgxMyUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDA4MTNUMjExOTI5WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9OTg2N2YxNTAwOGNjNWQ1OTcwYWMwNzE1NmZkZmQ4MjM5NDg3NzM5Nzk3Mjg2ODNiNTY2YTc5MzVkMGFhN2NiYyZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.imJMbtyr6uUywFKWlth9f0DgRO-hyDtl2JjVoIkygMo)

@davidkircos this is fixed.  Please test once the branch deploys.

2024-08-13 23:47 UTC, davidkircos commented
> > Can not download .grid file ![CleanShot 2024-08-09 at 16 17 36@2x](https://private-user-images.githubusercontent.com/3479421/356766004-46957263-406f-4e11-a334-068d29fdf568.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjM1ODQyNjksIm5iZiI6MTcyMzU4Mzk2OSwicGF0aCI6Ii8zNDc5NDIxLzM1Njc2NjAwNC00Njk1NzI2My00MDZmLTRlMTEtYTMzNC0wNjhkMjlmZGY1NjgucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDgxMyUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDA4MTNUMjExOTI5WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9OTg2N2YxNTAwOGNjNWQ1OTcwYWMwNzE1NmZkZmQ4MjM5NDg3NzM5Nzk3Mjg2ODNiNTY2YTc5MzVkMGFhN2NiYyZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.imJMbtyr6uUywFKWlth9f0DgRO-hyDtl2JjVoIkygMo)
> 
> @davidkircos this is fixed. Please test once the branch deploys.

Downloading files seems to work for me!

2024-08-15 19:02 UTC, ddimaria commented
> Importing 0.5M file fails, this works in main and qa.
> 1M and above file fails on main and qa.
> Files link: https://github.com/datablist/sample-csv-files

Resolved

2024-08-20 19:39 UTC, davidkircos approved these changes

2024-08-20 19:39 UTC, merged