feat: add keyboard shortcuts
quadratichq/quadratic pull request #1612
Opened 2024-07-26 01:31 UTC by AyushAgrawal-A2

part of #1536 

* [x]  Default JSON for shortcut default theme
* [x]  F2: edit cell
* [x]  Support both Ctrl + Shift + PageUp / Ctrl + Shift + PageDown **AND** option + up-arrow, option + down-arrow **AND** option + right arrow/option + left arrow: go to next/prior sheet (this covers as close as possible to all bases for both mainstream spreadsheets)
* [x]  Ctrl + d: fill down from the cell above
* [x]  Ctrl + r: fill right from the cell to the left
* [x]  Shift + space: select row
* [x]  Ctrl + space: select column

from old PR #1545 on from fork

2024-07-29 23:46 UTC, davidkircos requested changes
This is great! I like the design. 

Fix Cmd + S in the code editor and the functionality looks like it's all there

2024-07-29 23:46 UTC, davidkircos commented on quadratic-client/src/app/keyboard/defaults.ts
> +    },
It does not appear to work for save and run while the code editor is open. Command + Enter still does, though.

2024-07-29 23:46 UTC, davidkircos commented on quadratic-client/src/app/keyboard/defaults.ts
> +    action: 'show_code_editor',
rename to `show_cell_type_menu`?

2024-07-30 00:13 UTC, AyushAgrawal-A2 commented on quadratic-client/src/app/keyboard/defaults.ts
> +    },
done

2024-07-30 00:13 UTC, AyushAgrawal-A2 commented on quadratic-client/src/app/keyboard/defaults.ts
> +    action: 'show_code_editor',
done

2024-07-30 02:35 UTC, davidkircos requested changes
We need to disable command + s everywhere except when the cell editor is open. Otherwise the browser opens the save dialog when the code editor isn't open

![CleanShot 2024-07-29 at 20 34 15@2x](https://github.com/user-attachments/assets/95f22c86-e8e5-430f-9e6c-01838c791a2e)

2024-07-30 03:04 UTC, AyushAgrawal-A2 commented
> We need to disable command + s everywhere except when the cell editor is open. Otherwise the browser opens the save dialog when the code editor isn't open

@davidkircos 
done.
I changed event capture for viewport when trying to get ctrl+pageup to work. forgot to remove it. now behaviour is same as before.

2024-07-30 03:36 UTC, davidkircos approved these changes
Functionality looks great to me! 

Can merge into `qa` after code review from @davidfig

2024-07-30 11:04 UTC, davidfig approved these changes

2024-07-30 11:10 UTC, davidfig approved these changes

2024-07-30 11:42 UTC, merged