Rust core formula store
quadratichq/quadratic pull request #164
Opened 2022-12-03 18:00 UTC by davidkircos

2022-12-03 18:03 UTC, davidkircos commented on quadratic-core/src/grid/controller.rs
> +    }
Is there a better way to get a read only ref to grid from GridController?

2022-12-03 18:04 UTC, davidkircos commented on quadratic-core/src/tests/gc_deps.rs
> +        let r_cell = form.eval(t.grid().get_grid(), Pos { x: 1, y: 0 }).unwrap();
This is sort of an awkward call `t.grid().get_grid()`

Maybe the first function should be renamed `t.grid_controller().grid()` ?

2022-12-04 00:34 UTC, HactarCE requested changes

2022-12-04 00:37 UTC, davidkircos commented on quadratic-core/src/codestore/store.rs
> +        write!(f, "CodeStore {{ code: {:?} }}", self.code)
Removed Display impl

2022-12-04 00:39 UTC, davidkircos commented on quadratic-core/src/codestore/store.rs
> +        if code_cell_or_none.is_some() {
can you show me what you mean by `if let Some(...) = ...`

2022-12-04 00:41 UTC, merged

2022-12-04 00:42 UTC, HactarCE commented on quadratic-core/src/codestore/store.rs
> +        if code_cell_or_none.is_some() {
```rs
if let Some(code_cell) = code_cell_or_none {
    self.code.insert(pos, code_cell)
} else {
    self.code.remove(&pos)
}
```