Fixes number overflowing cell boundaries
quadratichq/quadratic pull request #1652
Opened 2024-08-06 14:35 UTC by davidfig

Fixes this:

![image](https://github.com/user-attachments/assets/d2066aff-c312-4ddb-b66b-f868d8960d37)

2024-08-06 15:04 UTC, ddimaria commented on quadratic-client/src/app/web-workers/renderWebWorker/worker/cellsLabel/CellLabel.ts
> +    const maxWidth = this.AABB.width - CURSOR_BORDER_SIZE * 2;
The changes in this file seem to be the only material changes.  Can you make a comment in the code for the significance of the the `* 2` portion?

2024-08-06 15:04 UTC, ddimaria commented on quadratic-client/src/app/web-workers/renderWebWorker/worker/cellsLabel/CellLabel.ts
> +        console.log(this.textWidth, this.AABB.width - CURSOR_BORDER_SIZE * 2);
Remove this log?

2024-08-06 15:04 UTC, ddimaria approved these changes

2024-08-06 22:54 UTC, davidkircos requested changes
There is a bug when rendering `111111111111`

https://github.com/user-attachments/assets/c92fe517-1b76-4172-8583-605947c8a641

2024-08-08 11:20 UTC, closed without merging

2024-08-08 11:20 UTC, davidfig commented
This has a better fix in #1668. Thanks @AyushAgrawal-A2!