fix: SharedArrayBuffer on safari
quadratichq/quadratic pull request #1677
Opened 2024-08-08 20:36 UTC by AyushAgrawal-A2

2024-08-08 21:11 UTC, davidkircos commented
This blocks:
- [ ] S3 images
- [ ] Sanity 
- [ ] All other non same origin requests

2024-08-08 23:16 UTC, davidkircos requested changes
This breaks:

S3 images
Sanity
Helpdesk
All other non same origin requests

2024-08-18 08:15 UTC, AyushAgrawal-A2 commented
@davidkircos
Sanity and S3 Images work now

2024-08-20 02:15 UTC, AyushAgrawal-A2 commented
I had to change Radix UI's Avatar component to MUI as the former was not passing in crossOrigin attribute to img tag

2024-08-21 23:09 UTC, AyushAgrawal-A2 commented
Changes:
- Added custom avatar component, removed @radix-ui/react-avatar
- Removed live chat
- fixed google tags cors error

2024-08-22 19:56 UTC, jimniels commented on quadratic-client/src/shared/components/Avatar.tsx
> +          style={{ ...stylePreset, ...style }}
@AyushAgrawal-A2 if _all_ of our avatars are going to need `crossOrigin=anonymous` why not just put it in here at the base component? Then whenever you use `<Avatar>` you don't have to remember to add that extra attribute.

In other words, make `crossOrigin=anonymous` opt-out rather than opt-in (is there anywhere in our code where we would even opt-out of this right now?)

2024-08-22 19:58 UTC, jimniels commented on quadratic-client/src/shared/components/Avatar.tsx
> +          style={{ ...stylePreset, ...style }}
Actually same idea with `src`

It seems everywhere you're implementing Avatar you're also having to do

`src=getAuth0AvatarSrc(...)}`

so why not do this in the base component too?

2024-08-22 19:59 UTC, jimniels commented on quadratic-client/src/shared/components/Avatar.tsx
> +  fallbackSrc?: string;
What is `fallbackSrc`? Like are you actually using this somewhere?

2024-08-22 20:03 UTC, jimniels commented on quadratic-client/src/dashboard/components/DashboardSidebar.tsx
> +              backgroundColor: colors.quadraticSecondary,
If the `<Avatar>` component has built-in sizing, seems like we should just be using it rather than hard-coding these values (which are just duplicates of what's already in the component)?

`width`, `height`, and `fontSize` are all controlled by the `size` prop, so just use that, no? (and this is just the default size anyway, so you don't even need it)

and `borderRadius` is already set to `50%` in the base component, so no need for it here?

And I would just leave the `backgroundColor` here to be whatever the default is.

so I don't think you need any of these styles

2024-08-22 20:07 UTC, jimniels commented on quadratic-client/src/shared/components/Avatar.tsx
> +import React, { ImgHTMLAttributes } from 'react';
I feel like we should leave a todo at the top of this file that talks about how this is should be the de-facto Avatar component going forward, so eventually all occurrences of `<Avatar>` elsewhere in the code base (like from MUI) should be swapped over to this one. 

That's the goal, right?

2024-08-22 20:15 UTC, jimniels commented on quadratic-client/src/dashboard/components/FilesListItemCore.tsx
> +              className="h-6 w-6 text-muted-foreground"
Seems like you can remove this `className` because it should just take on the base default styles

2024-08-22 20:21 UTC, jimniels commented on quadratic-client/src/app/ui/menus/CodeEditor/AiAssistant.tsx
> +                    backgroundColor: colors.quadraticSecondary,
Similar comment to [this one](https://github.com/quadratichq/quadratic/pull/1677/files#r1727742005). I don't think you should pass any of these. They're just duplicates of what's already in `<Avatar>` (except `backgroundColor` and I think you should just let that be the default here, e.g. a dull gray)

2024-08-22 20:22 UTC, jimniels commented on quadratic-client/src/app/ui/menus/CodeEditor/AiAssistant.tsx
> +                    borderRadius: '50%',
Similar to the above. No need to override the style values already present in the base avatar component (width, height, fontSize, border-radius)

2024-08-22 20:24 UTC, jimniels reviewed
All the stuff that fixes Safari looks good to me 👍 

Left some clarifying comments and also feedback related to the generalized `<Avatar>` component.

2024-08-22 21:29 UTC, AyushAgrawal-A2 commented on quadratic-client/src/shared/components/Avatar.tsx
> +          style={{ ...stylePreset, ...style }}
@jimniels 
I am assuming that all request will not be cross origin, we can make it opt out, I am OK either ways

same with `src=getAuth0AvatarSrc(...)}`, I am OK, can be plugged directly into Avatar component, should be OK
it is required because of the intermediary gravatar link provided by Auth0

2024-08-22 21:30 UTC, AyushAgrawal-A2 commented on quadratic-client/src/shared/components/Avatar.tsx
> +  fallbackSrc?: string;
I wanted to do level 1 fallback to another source, level 2 to child string / component, I removed it while debugging and forgot to add it back

2024-08-22 21:32 UTC, AyushAgrawal-A2 commented on quadratic-client/src/dashboard/components/DashboardSidebar.tsx
> +              backgroundColor: colors.quadraticSecondary,
yup, we can clean these up... I kept it as a reference to preserve original values before my refactor

2024-08-22 21:35 UTC, AyushAgrawal-A2 commented on quadratic-client/src/shared/components/Avatar.tsx
> +import React, { ImgHTMLAttributes } from 'react';
I am not sure why we want to move away from MUI, I don't have a favourite. I am OK with whatever works
Also for easy components like this Avatar one, we can implement ourselves and avoid dependencies.
The remaining MUI <Avatar> components are the ones used with <AvatarGroup> parent component and have image stacking. I also do a custom component for that, if moving away from MUI is necessary.

2024-08-22 21:36 UTC, AyushAgrawal-A2 commented on quadratic-client/src/dashboard/components/FilesListItemCore.tsx
> +              className="h-6 w-6 text-muted-foreground"
i think styles from these tailwind classes are different from default ones, it is the value originally used here.

2024-08-22 22:44 UTC, jimniels commented on quadratic-client/src/shared/components/Avatar.tsx
> +  fallbackSrc?: string;
what were you falling back to? some generic image somewhere?

2024-08-22 22:48 UTC, jimniels commented on quadratic-client/src/shared/components/Avatar.tsx
> +import React, { ImgHTMLAttributes } from 'react';
The long-term plan is to move off MUI, so if we can remove it everywhere it won't be part of our bundle. I think that's a good goal to strive for, i.e. let's have the same `<Avatar>` component everywhere in the codebase.

> for easy components like this Avatar one, we can implement ourselves and avoid dependencies.

Precisely.

> The remaining MUI <Avatar> components are the ones used with <AvatarGroup>

I don't know that you have to do that in this PR. I just think it's good to leave a note in the component that "hey, this is the one we should be using going forward." And when we have a chance to move off the MUI avatar, let's do it! You can decide when is a good time based on your understanding of what it would take to move off MUI.

2024-08-22 22:49 UTC, jimniels commented on quadratic-client/src/dashboard/components/FilesListItemCore.tsx
> +              className="h-6 w-6 text-muted-foreground"
Remove it. h-6 and w-6 are just saying width/height 24px.

And the text color should be handled by the default <Avatar> component.

We don't need this having it's own one-off style that's different from the base <Avatar> component.

2024-08-22 22:51 UTC, AyushAgrawal-A2 commented on quadratic-client/src/shared/components/Avatar.tsx
> +  fallbackSrc?: string;
I wanted to take 2 src argument... one would have been a foreign request... one local default src or some stable source..
It is not committed in the pr yet

2024-08-22 22:51 UTC, jimniels commented on quadratic-client/src/shared/components/Avatar.tsx
> +          style={{ ...stylePreset, ...style }}
I feel like our avatar solution right now is to always reference files that aren't stored on the same origin (e.g. images we get from auth0) so putting it in the base avatar component makes sense to me.

I know if I have to go use an <Avatar> somewhere else in the code to put somebody's picture on screen, I'm going to forget to do `src={getAuth0AvatarSrc()}` as well as add crossOrigin.

That's my thought for putting it in the base component, so we don't have to remember to do those two things on every single Avatar component we use elsewhere.

2024-08-22 22:58 UTC, AyushAgrawal-A2 commented on quadratic-client/src/shared/components/Avatar.tsx
> +          style={{ ...stylePreset, ...style }}
Sure, will do

2024-08-22 23:00 UTC, AyushAgrawal-A2 commented on quadratic-client/src/shared/components/Avatar.tsx
> +import React, { ImgHTMLAttributes } from 'react';
I don't want to do it in this PR. This was about fixing cross origin and it turned into a MUI / Radix UI debate...
Happy to do it later, I have put all SAB related work on hold until cross-origin is fixed properly.
I really don't want any more pile on on this PR. I will add a TODO note.

2024-08-22 23:00 UTC, AyushAgrawal-A2 commented on quadratic-client/src/shared/components/Avatar.tsx
> +import React, { ImgHTMLAttributes } from 'react';
Will add a note

2024-08-27 02:45 UTC, davidkircos approved these changes
Functionality all seems to work for me!

I noticed an issue where JS `fetch` requests do not work in Safari, but I think this is a different issue. I believe those probably need to be proxied and are not today.

2024-08-27 02:48 UTC, davidkircos commented
AI Avatar doesn't load properly 
![CleanShot 2024-08-26 at 20 48 11@2x](https://github.com/user-attachments/assets/17e66d82-91f4-45f2-ba70-53cafc08753c)

2024-08-27 02:50 UTC, davidkircos requested changes
see previous comments

2024-08-27 05:39 UTC, AyushAgrawal-A2 commented
>AI Avatar doesn't load properly

@davidkircos
fixed

2024-08-27 21:28 UTC, davidkircos approved these changes

2024-08-27 21:28 UTC, merged