fix: when dragging on grid, ignore charts
quadratichq/quadratic pull request #1693
Opened 2024-08-10 00:24 UTC by AyushAgrawal-A2

closes #1686

2024-08-10 01:12 UTC, davidkircos requested changes
If you mouseUp over the graph the dragging isn't turned off.

I've found the most effective way to deal with this is to attach the mouseUp event to the window because then it is always triggered, even if the user drags off screen

2024-08-10 21:41 UTC, AyushAgrawal-A2 commented
> If you mouseUp over the graph the dragging gets stuck on.

Fixed

> I've found the most effective way to deal with this is to attach the mouseUp event to the window because then it is always triggered, even if the user drags off screen

It is already there

2024-08-11 16:28 UTC, davidkircos approved these changes

2024-08-11 16:28 UTC, merged

2024-08-11 16:28 UTC, davidkircos commented
Nice fix @AyushAgrawal-A2 !