feat: file import from New file dialog
quadratichq/quadratic pull request #1715
Opened 2024-08-14 08:06 UTC by AyushAgrawal-A2

- [x] File import from new dialog box
- [x] Redirect page based on upload context
- [ ] Drag and drop on dashboard
- [ ] Import progess

2024-08-19 23:31 UTC, davidkircos requested changes
When importing a single file, just open it after importing.

![CleanShot 2024-08-19 at 17 31 35@2x](https://github.com/user-attachments/assets/3043f5b8-6817-45a4-90a2-d925ff3abbb9)

2024-08-19 23:33 UTC, davidkircos requested changes
Show import drop files here only over files side of the dashboard. Don't overlay over the nav bar
![CleanShot 2024-08-19 at 17 32 20@2x](https://github.com/user-attachments/assets/2845da16-b697-4c03-9716-d01e3a08c6c2)

2024-08-19 23:37 UTC, davidkircos requested changes
Functionality works great! 

Needs to be updated with the base branch, and rust code review.

2024-08-20 17:36 UTC, ddimaria commented on quadratic-client/src/app/gridGL/loadAssets.ts
> +  if (!Loader.shared.resources[name]) {
Do we want some error or a log to show that the resource doesn't exist?

2024-08-20 17:37 UTC, ddimaria commented on quadratic-client/src/app/helpers/files.ts
> +export const getFileType = (file: File) => {
I think moving these here makes a lot of sense.

2024-08-20 17:43 UTC, jimniels commented on quadratic-client/src/router.tsx
> +              shouldRevalidate={({ currentParams, nextParams }) => currentParams.uuid !== nextParams.uuid}
@AyushAgrawal-A2 for my own edification, why this change? if the file uuid is changing (in the app) then you're navigating to a new place and that should be a whole document reload, no?

2024-08-20 17:45 UTC, jimniels commented on quadratic-client/src/shared/shadcn/ui/progress.tsx
> +    className={cn('relative h-4 w-full overflow-hidden rounded bg-[#F2F5F9]', className)}
Why the hard-coded value? Were you pulling this from Figma? Feel like we should stick to `bg-primary/20`

2024-08-20 17:47 UTC, jimniels approved these changes
Reviewed the ts. Two comments but this LGTM. Will review more of the functionality when this gets merged into the base branch and we use it along with all the other functionality.

2024-08-20 17:50 UTC, AyushAgrawal-A2 commented on quadratic-client/src/shared/shadcn/ui/progress.tsx
> +    className={cn('relative h-4 w-full overflow-hidden rounded bg-[#F2F5F9]', className)}
@jimniels 
yup, these were direct figma values, didn't know we have tailwind equivalents

2024-08-20 17:51 UTC, jimniels commented on quadratic-client/src/shared/shadcn/ui/progress.tsx
> +    className={cn('relative h-4 w-full overflow-hidden rounded bg-[#F2F5F9]', className)}
Yeah anything in Figma is just an approximation of what the base shad/cn values are doing. So let's keep it at `bg-primary/20`

2024-08-20 17:51 UTC, AyushAgrawal-A2 commented on quadratic-client/src/router.tsx
> +              shouldRevalidate={({ currentParams, nextParams }) => currentParams.uuid !== nextParams.uuid}
@jimniels 
When creating a new file from App (i.e. open file) using new dialog box, the document needs to reload, if we want to switch to that file.
I was not reloading without this change

2024-08-20 18:59 UTC, ddimaria commented on quadratic-client/src/app/web-workers/quadraticCore/worker/core.ts
> +    sequenceNum: number
There is a fair amount of duplication in this file that it could merit some abstractions to DRY things up.

2024-08-20 19:29 UTC, AyushAgrawal-A2 commented on quadratic-client/src/app/gridGL/loadAssets.ts
> +  if (!Loader.shared.resources[name]) {
Nope, the issue was when opening a new file from App, resources were being loaded again, which resulting in error.
We did not have the functionality of opening a new file from the app (i.e. when another file is already open).

2024-08-20 19:57 UTC, AyushAgrawal-A2 commented on quadratic-client/src/shared/shadcn/ui/progress.tsx
> +    className={cn('relative h-4 w-full overflow-hidden rounded bg-[#F2F5F9]', className)}
done

2024-08-20 20:41 UTC, ddimaria reviewed
Looks great, just some comments and questions, mostly non-blocking.  I like the move away from sending mutable references for most of the functions 💯

2024-08-20 20:41 UTC, ddimaria commented on quadratic-core/src/controller/execution/execute_operation/mod.rs
> +            if cfg!(target_family = "wasm") || cfg!(test) {
@davidfig You know more about the `transaction.is_server()` code, are the changes in these files all good?

2024-08-20 20:41 UTC, ddimaria commented on quadratic-core/src/controller/execution/receive_multiplayer.rs
> +            transaction_name: transaction_name.unwrap_or(TransactionName::Unknown),
Should we make this an error case or in some way notify via `dbgjs!` so that this un-anticipated state is known?

2024-08-20 20:41 UTC, ddimaria commented on quadratic-core/src/controller/mod.rs
> +    pub fn into_grid(self) -> Grid {
Consider implementing the From/Into trait as it's more idiomatic.

2024-08-20 20:41 UTC, ddimaria commented on quadratic-core/src/controller/operations/import.rs
> +        let total_rows = sheets
Nice 💯

2024-08-20 20:41 UTC, ddimaria commented on quadratic-core/src/controller/user_actions/import.rs
> +    /// Using `cursor` here also as a flag to denote import into new / existing file.
Much better doc message 🙌

2024-08-20 20:41 UTC, ddimaria commented on quadratic-core/src/grid/file/mod.rs
> +fn import_json(file_contents: String) -> Result<Grid> {
We previously avoided allocating to the heap.  What's the justification for changing this?

2024-08-20 20:41 UTC, ddimaria commented on quadratic-core/src/grid/file/v1_6/file.rs
> +                        id,
Nice!

2024-08-20 20:41 UTC, ddimaria commented on quadratic-rust-shared/src/error.rs
> +    #[error("Error with Request: {0}")]
`Reqwest` was intentional before as that's the name of the crate used.

2024-08-20 21:41 UTC, AyushAgrawal-A2 commented on quadratic-core/src/grid/file/mod.rs
> +fn import_json(file_contents: String) -> Result<Grid> {
to take ownership, convert to json and drop it immediately releasing memory

2024-08-20 21:43 UTC, AyushAgrawal-A2 commented on quadratic-core/src/controller/mod.rs
> +    pub fn into_grid(self) -> Grid {
here into_ is used in line with rust convention when we are consuming original value, here I am consuming the grid from controller, to take ownership and consume data rather than cloning, to save memory

2024-08-20 21:47 UTC, AyushAgrawal-A2 commented on quadratic-core/src/controller/execution/execute_operation/execute_sheets.rs
> +            if let Ok(sheet) = schema.clone().into_latest() {
schema is also pushed to forward transactions, a clone is required here

2024-08-20 22:09 UTC, davidfig approved these changes

2024-08-20 22:09 UTC, davidfig commented on quadratic-core/src/controller/execution/control_transaction.rs
> +        if cfg!(target_family = "wasm") {
Should be fine. Only server uses ::Server, and it doesn't need any client updates.

2024-08-20 22:09 UTC, davidfig commented on quadratic-core/src/controller/execution/receive_multiplayer.rs
> +            transaction_name: transaction_name.unwrap_or(TransactionName::Unknown),
transaction_name is not super important. We don't even use it yet. (I was hoping to use it as part of Kernel to report on what core was doing--but never got to it.)

2024-08-20 22:09 UTC, davidfig commented on quadratic-core/src/controller/operations/import.rs
> +        file: Vec<u8>,
Why the move away from slice?

2024-08-20 22:09 UTC, davidfig commented on quadratic-core/src/controller/user_actions/import.rs
> +        file: Vec<u8>,
ditto on the slice

2024-08-20 22:09 UTC, davidfig commented on quadratic-core/src/controller/user_actions/import.rs
> +    /// Using `cursor` here also as a flag to denote import into new / existing file.
Was the overload of cursor to avoid redoing the messages? I'm okay with it, but usually better to add another variable.

2024-08-20 22:09 UTC, davidfig commented on quadratic-core/src/grid/file/current.rs
> +pub fn export_rows_code_runs(sheet: &Sheet) -> Vec<(current::Pos, current::CodeRun)> {
Nice change. If you're going to pull these out, it's worth a test (assuming you also pulled out import_row_code_runs.

2024-08-20 22:59 UTC, AyushAgrawal-A2 commented on quadratic-client/src/app/web-workers/quadraticCore/worker/core.ts
> +    sequenceNum: number
Will do cleanup directly in jim's onboarding branch

2024-08-20 23:00 UTC, AyushAgrawal-A2 commented on quadratic-core/src/controller/operations/import.rs
> +        file: Vec<u8>,
to take ownership, use data without cloning and drop the rest asap, this saves memory usage

2024-08-20 23:00 UTC, AyushAgrawal-A2 commented on quadratic-core/src/controller/user_actions/import.rs
> +    /// Using `cursor` here also as a flag to denote import into new / existing file.
cursor will only be there when importing into existing sheet, felt redundant to add a boolean flag to denote this

2024-08-20 23:02 UTC, AyushAgrawal-A2 commented on quadratic-core/src/grid/file/current.rs
> +pub fn export_rows_code_runs(sheet: &Sheet) -> Vec<(current::Pos, current::CodeRun)> {
this was the only operation in export_sheet function, which was not separate... now it matches the rest of the exports

2024-08-20 23:06 UTC, AyushAgrawal-A2 commented on quadratic-rust-shared/src/error.rs
> +    #[error("Error with Request: {0}")]
reverted

2024-08-20 23:36 UTC, ddimaria commented on quadratic-core/src/controller/mod.rs
> +    pub fn into_grid(self) -> Grid {
This pedantic, so we can skip.  But I would think you're going from a GridController into a Grid.  Another way to implement this is to implement the deref trait for GridController, assuming it's just a wrapper around a Grid.

2024-08-20 23:36 UTC, ddimaria approved these changes

2024-08-21 04:15 UTC, merged