fix: javaScript charts not anchored to their cell when resizing columns
quadratichq/quadratic pull request #1794
Opened 2024-08-25 03:24 UTC by AyushAgrawal-A2

closes #1777

2024-08-25 04:50 UTC, davidkircos commented
This fixes the issue but seems to introduce a new bug to autoresizing blank columns.

Blank columns used to resize to the default column size on double click. Now, they grow by a few px. I verified this behavior is only in this branch and not in main. See video


https://github.com/user-attachments/assets/76136afe-67b1-445f-a5c2-1a0c4a43c305

2024-08-25 05:05 UTC, AyushAgrawal-A2 commented
>Blank columns used to resize to the default column size on double click. Now, they grow by a few px. I verified this behavior is only in this branch and not in main. See video

yup, i saw that too, already on my list

2024-08-25 12:42 UTC, davidfig approved these changes

2024-08-27 03:00 UTC, davidkircos requested changes
bugfix still requested

2024-08-28 20:37 UTC, davidkircos approved these changes

2024-08-28 20:38 UTC, merged