feat: ability to have a cell be a clickable link
quadratichq/quadratic pull request #1823
Opened 2024-08-30 11:52 UTC by AyushAgrawal-A2

closes #758

2024-09-03 14:47 UTC, luke-quadratic commented
Doesn't seem to be working 
![CleanShot 2024-09-03 at 08 46 59](https://github.com/user-attachments/assets/d37b2677-9a6f-43ee-a6ff-9c225097bcf0)

2024-09-03 14:49 UTC, luke-quadratic commented
@jimniels @davidkircos @AyushAgrawal-A2 These powder blues in the sheet are so light - wdyt about matching more with the direction colors have started to go in the app? The colors are now split and disjointed with blue and powder blue in the same experiences 

![CleanShot 2024-09-03 at 08 48 57@2x](https://github.com/user-attachments/assets/ea081fab-6ad1-4445-aefa-3b734e33492e)

2024-09-03 14:51 UTC, AyushAgrawal-A2 commented
@luke-quadratic 
>Doesn't seem to be working
currently it is Cmd + click to open, cursor pointer pn hover is only meant to indicate it is clickable... open to changing this behaviour

2024-09-03 15:07 UTC, jimniels commented
> @jimniels @davidkircos @AyushAgrawal-A2 These powder blues in the sheet are so light - wdyt about matching more with the direction colors have started to go in the app?

Agree that this blue we use is not a very high contrast color and surely fails accessibility.

FWIW: I'm planning on doing this in the "new app design work" where I want to make the cursor and other elements the same "blue" as we use elsewhere, e.g.

![CleanShot 2024-09-03 at 09 04 38@2x](https://github.com/user-attachments/assets/486e8c09-c618-4178-8e19-6f57f502e91b)

May as well start that work in this PR I would say.

2024-09-11 20:43 UTC, davidkircos requested changes
Links don't work for me

https://github.com/user-attachments/assets/138b88bf-5090-4c55-bc04-39c7ebbde96c

2024-09-11 23:24 UTC, luke-quadratic commented
> Links don't work for me
> 
>  CleanShot.2024-09-11.at.14.42.34.mp4

@davidkircos see conversation above, cmd+click

2024-09-16 23:46 UTC, luke-quadratic approved these changes
works great on functionality

2024-09-17 12:23 UTC, davidfig approved these changes

2024-09-17 12:23 UTC, davidfig commented
Looks much better

2024-09-19 12:40 UTC, davidfig approved these changes

2024-09-20 17:14 UTC, jimniels commented
The link tooltip should have a delay. Right now it appears _immediately_ when you hover over it, so if you're moving your cursor across the sheet and go across a cell it's going to show even if you didn't mean to. It should require a few hundred millisecond hover intention to show it (this is how VSCode does it). 

If we don't have it, it gets especially weird when you have lots of links because the tooltip triggers for every link as you move it across the sheet.


https://github.com/user-attachments/assets/46abd14e-47b0-4036-8287-3df2cee89946

2024-09-20 17:25 UTC, jimniels commented
In tooltips, when we have a keyboard shortcut, we de-emphasize the shortcut itself. Example:

![CleanShot 2024-09-20 at 11 23 18@2x](https://github.com/user-attachments/assets/9ff745e5-b18f-4b2a-bcdf-fd3854945980)

We should do the same here. Something like:

`Open link <span className="opacity-50">(⌘+click)</span>`

2024-09-23 15:58 UTC, jimniels commented
**re: Positioning**

> I think the dialogue should be better aligned with the grid, though. Maybe exactly the top left corner of the current cell?

I think the tooltip should work like a tooltip and therefore take its cues for alignment and positioning based on the current position of the user’s cursor. I don't think it should factor in what the grid looks like because, for example, you might be zoomed in or zoomed out and thus the grid's positioning and sizing will change. 

For example, if we align the tooltip on the top left of the cell where the link originates, then the UX is really weird when you have a long link and hover the end of it.

![CleanShot 2024-09-23 at 09 40 07](https://github.com/user-attachments/assets/81fd9e93-9ca2-4c2b-b3a0-f79519c24048)

IMO if it looks like a tooltip, it should act like one and therefore appear in proximity to the user's current cursor position regardless of anything else on screen.

---

**Bug: zoom levels**

If you zoom in and hover a link cell, the tooltip is all pixelated and small.

![CleanShot 2024-09-23 at 09 43 20@2x](https://github.com/user-attachments/assets/27c43598-eff3-4056-9397-181c67301f53)

---

**Enhancement: hover interactions**

VSCode provides additional interaction cues when you try to interact with a link. If you hover a link, it gets a subtle background color behind the link text that displays simultaneously with the tooltip, helping bolster the feeling that this element can be interacted with.

Additionally, once you key down on CMD, the link's color changes further bolstering the feeling that this is a link.

![CleanShot 2024-09-23 at 09 42 46](https://github.com/user-attachments/assets/4498fc36-c972-43e8-b022-69eab5520729)

I think it'd be nice if we added one (or both) of these.

The background color one could get tricky, especially with cells having the option to have different background colors. So maybe that one we can put on the back burner...

But the text color perhaps we could try a little dash of CSS to help with this effect? I get that people can color their links so we can't depend on them always being blue and thus we can't just set a different shade of blue for the effect.

Perhaps we could use the `filter` property so that when a user hovers a link (or maybe it's on the "cmd" keydown, I'm not entirely sure, play with it) we add a rule along the lines of:

`filter: brightness(1.5)`

Maybe it's a combination of `brightness` and `saturation`, and maybe we don't turn the brightness up but rather turn it down. I'm not sure, I'd say feel free to play with it. But something that adds an additional cue that the link can be interacted with would be a nice touch.

2024-09-23 19:11 UTC, AyushAgrawal-A2 commented on quadratic-client/src/app/ui/menus/CommandPalette/commands/Text.tsx
> +    },
not in scope of this PR, command group refactoring is Pending and should be done together

2024-09-23 20:08 UTC, jimniels approved these changes

2024-09-24 16:42 UTC, davidkircos approved these changes

2024-09-25 01:54 UTC, merged