fix: inline editor arrow key interactions (edit & enter states)
quadratichq/quadratic pull request #1972
Opened 2024-10-15 16:02 UTC by AyushAgrawal-A2

closes #1961 

Mode indicator: (for testing, will change)
`Insert Cell Ref` Mode: White Icon
![image](https://github.com/user-attachments/assets/0e92519e-3bd4-4bf4-9b19-8ae6a1e8597d)

`Navigate Text` Mode: Black Icon
![image](https://github.com/user-attachments/assets/8c657040-61a6-4c85-8896-52d938f18b16)

2024-11-20 18:14 UTC, jimniels requested changes
Can we provide some spacing/padding around the icon? For example, this this screenshot, the icon size is 15x15px (instead of 20x20). Gives it a little more space to breathe.

![CleanShot 2024-11-20 at 11 09 33@2x](https://github.com/user-attachments/assets/6055864c-c088-4627-9055-676db27ea12f)

2024-11-20 19:40 UTC, AyushAgrawal-A2 commented
> Can we provide some spacing/padding around the icon? For example, this this screenshot, the icon size is 15x15px (instead of 20x20). Gives it a little more space to breathe.
> 
> ![CleanShot 2024-11-20 at 11 09 33@2x](https://private-user-images.githubusercontent.com/1316441/388215147-6055864c-c088-4627-9055-676db27ea12f.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzIxMzA2NzksIm5iZiI6MTczMjEzMDM3OSwicGF0aCI6Ii8xMzE2NDQxLzM4ODIxNTE0Ny02MDU1ODY0Yy1jMDg4LTQ2MjctOTA1NS02NzZkYjI3ZWExMmYucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MTEyMCUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDExMjBUMTkxOTM5WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9YzU3ZTk2MWJhOGIwNTRhMGVmMTc0ZTNlYjE1YWRlMzE1NzcxOTNlYjZhNGM4MTBiNzM2ZGNkOWM0OWFiNjc4NiZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QifQ.Vgup7RC6O48pcAZdYMzQ6CA9NRDiHJMifxuIqNhLPuY)

@jimniels 
done

2024-11-21 16:15 UTC, jimniels approved these changes
With the change where this is the default state for entering text into empty prompts:

![CleanShot 2024-11-21 at 09 15 20@2x](https://github.com/user-attachments/assets/6814eae3-9454-40a0-8d53-d97c693c6993)

I'm good with these current changes

2024-11-21 16:57 UTC, davidkircos approved these changes

2024-11-21 16:57 UTC, merged