build images on pr open/push
quadratichq/quadratic pull request #2140
Opened 2024-12-20 20:27 UTC by AyushAgrawal-A2

closes #2075

2024-12-25 23:47 UTC, AyushAgrawal-A2 commented on package.json
> +    "docker:build": "ECR_OR_BUILD=build docker compose --profile all --env-file .env.docker up"
`npm run docker` -> pull latest production images from ecr and run app in docker
`npm run docker:build` -> build locally and run app in docker

2025-01-02 18:29 UTC, davidkircos commented on infra/aws-cloudformation/quadratic-selfhost.yml
> +      Name: !Sub "${ImageTag}.quadratic-selfhost.com."
Move to quadratic-preview.com

2025-01-02 21:39 UTC, AyushAgrawal-A2 commented on infra/aws-cloudformation/quadratic-selfhost.yml
> +      Name: !Sub "${ImageTag}.quadratic-selfhost.com."
done

2025-01-03 20:20 UTC, davidkircos commented on .github/workflows/ci.yml
> +  cancel-in-progress: true
This group name is shared across all PRs and production.

So you'd want to add the branch name to the group name. [See here](https://stackoverflow.com/questions/70928424/limit-github-action-workflow-concurrency-on-push-and-pull-request)

2025-01-03 20:21 UTC, davidkircos commented on .github/workflows/ci.yml
> +  test_core:
Some job names are explicitly required to pass for merging into `main`.

We will need to update this list if we are renaming jobs.

2025-01-03 20:23 UTC, davidkircos commented on .github/workflows/ci.yml
> +          cargo test -- --test-threads=4
4 threads with 2 CPUs?

2025-01-03 20:25 UTC, davidkircos commented on .github/workflows/production-publish-images.yml
> -      - self-hosting-setup #remove
nice

2025-01-03 20:26 UTC, davidkircos commented on .github/workflows/production-publish-images.yml
> +  cancel-in-progress: true
I think we should let previous jobs finish for consistency. What if half the images were built and pushed when it was canceled?

2025-01-03 20:28 UTC, davidkircos commented on .github/workflows/ci.yml
> +  cancel-in-progress: true
```
concurrency:
  group: pr-${{ github.event.pull_request.number }}
 ```

2025-01-03 20:31 UTC, davidkircos commented on infra/aws-cloudformation/quadratic-selfhost.yml
rename quadratic-preview.yml

2025-01-03 20:31 UTC, AyushAgrawal-A2 commented on .github/workflows/ci.yml
> +  test_core:
Got it.
FYI, this is not just renaming... I broke rust tests into 3 tests (core, multiplayer and connections) so that all run in parallel and CI run finishes faster. This used to take ~10 before for all crates.

2025-01-03 20:32 UTC, davidkircos commented on .github/workflows/staging-build-deploy-images.yml
> +          echo "ECR_URL=$ECR_URL" >> $GITHUB_OUTPUT
Do you ever clean up old repos?

2025-01-03 20:32 UTC, davidkircos commented on .github/workflows/staging-build-deploy-images.yml
> +          echo "REPO_NAME=quadratic-${{ matrix.service }}" >> $GITHUB_OUTPUT
This is global. Do we need to add part to the name for each branch? How do different branches know to pull different images?

2025-01-03 20:34 UTC, AyushAgrawal-A2 commented on .github/workflows/staging-build-deploy-images.yml
> +          echo "REPO_NAME=quadratic-${{ matrix.service }}" >> $GITHUB_OUTPUT
images have a pr-${number} tag i.e. `pr-2140` for this PR.. they are pulled based on tag from each repo... we have repos for each service

2025-01-03 20:36 UTC, davidkircos commented on .github/workflows/staging-build-deploy-images.yml
> +            --output text)
How does it know to use the images you build above? If there are more than one branch, how do they reference the correct images?

2025-01-03 20:38 UTC, davidkircos requested changes
`preview-branches.yml` is still in this branch, so this will still be launching Pulumi stacks as well. we would want to disable that except on `qa` or a branch with a specific tag

2025-01-03 20:40 UTC, davidkircos commented on .github/workflows/staging-build-deploy-images.yml
> +          edit-mode: replace
I don't see the deployment success or deployment failure messages in Github

2025-01-03 20:45 UTC, ddimaria commented on .env.docker
> +DEV=false
This variable seems overly general for the specific option it supports.

2025-01-03 20:48 UTC, ddimaria commented on Dockerfile.dev
> +FROM node:18
Consider using multi-stage here and running in a minimal container.

2025-01-03 20:49 UTC, AyushAgrawal-A2 commented on .github/workflows/staging-build-deploy-images.yml
> +            --output text)
only the last image will have the tag pr-${number} in the repo... pr-${number} is the id for everything on aws, stack, all recourse id and image tag... old images will have no tags.. will be easy to delete

2025-01-03 20:51 UTC, AyushAgrawal-A2 commented on .github/workflows/staging-build-deploy-images.yml
> +            --output text)
the stack pulls in images with the ImageTag (pr-${number}) passed as parameter to it on stack creation
![image](https://github.com/user-attachments/assets/ba2f53e3-954c-4bb6-9679-875eee8ee236)

2025-01-03 20:54 UTC, AyushAgrawal-A2 commented on .github/workflows/staging-build-deploy-images.yml
> +          edit-mode: replace
it is buried inside hidden commits as this was added later... best way to test full functionality is to open a new pr using this branch as base

![image](https://github.com/user-attachments/assets/91fd7822-e24b-4024-a533-8bcea08f71e5)

![image](https://github.com/user-attachments/assets/019120f5-a9be-4a77-8402-0d5da5540d96)

2025-01-03 20:55 UTC, ddimaria commented on quadratic-connection/src/config.rs
> +fn default_host() -> String {
What is the reasoning behind supporting a default host and port?

2025-01-03 20:57 UTC, AyushAgrawal-A2 commented on Dockerfile.dev
> +FROM node:18
everything runs in a single container here... this docker file is to run entire app with node dev in docker... needs to be in a single container

2025-01-03 20:57 UTC, ddimaria commented on quadratic-files/src/config.rs
> +fn default_host() -> String {
Same comment here on defaults.  I built these to fail at startup if all required variables aren't included.

2025-01-03 20:58 UTC, AyushAgrawal-A2 commented on quadratic-files/src/config.rs
> +fn default_host() -> String {
when running node dev in docker... I need to pass `HOST` and `PORT` for multiplayer, files and connection... but all of them use the same name `HOST` and `PORT`... I resorted to having defaults that dealing with name conflicts
![image](https://github.com/user-attachments/assets/756ddd0e-72f3-4078-a7b8-19504474dccc)

2025-01-03 20:59 UTC, AyushAgrawal-A2 commented on quadratic-connection/src/config.rs
> +fn default_host() -> String {
when running node dev in docker... I need to pass `HOST` and `PORT` for multiplayer, files and connection... but all of them use the same name `HOST` and `PORT`... I resorted to having defaults that dealing with name conflicts

![image](https://github.com/user-attachments/assets/756ddd0e-72f3-4078-a7b8-19504474dccc)

2025-01-03 21:01 UTC, AyushAgrawal-A2 commented on .github/workflows/ci.yml
> +          cargo test -- --test-threads=4
done

2025-01-03 21:01 UTC, AyushAgrawal-A2 commented on .github/workflows/production-publish-images.yml
> +  cancel-in-progress: true
done

2025-01-03 21:01 UTC, AyushAgrawal-A2 commented on infra/aws-cloudformation/quadratic-selfhost.yml
done

2025-01-03 21:08 UTC, AyushAgrawal-A2 commented on .github/workflows/ci.yml
> +  cancel-in-progress: true
I want to cancel old runs when a new commit is pushed... I think new group name should work

2025-01-03 21:21 UTC, AyushAgrawal-A2 commented on .env.docker
> +DEV=false
renamed to CLIENT_DEV

2025-01-03 21:21 UTC, davidkircos commented on .github/workflows/ci.yml
> +  test_core:
Sounds good, just calling it out here so we remember

2025-01-03 21:22 UTC, davidkircos commented on infra/aws-cloudformation/quadratic-selfhost.yml
Is all the naming in the branch now consistent? Should we distinguish full stack previews from single instance previews in our naming convention?

2025-01-03 21:23 UTC, davidkircos commented on .github/workflows/staging-build-deploy-images.yml
> +          edit-mode: replace
Is there a way to show it not just as a comment but an actual "Deployment" so it shows up in this section? 
![CleanShot 2025-01-03 at 14 22 57@2x](https://github.com/user-attachments/assets/0f19d37a-9ddd-4c0b-95ba-290913f1fb73)

2025-01-04 10:09 UTC, AyushAgrawal-A2 commented on quadratic-connection/src/config.rs
> +fn default_host() -> String {
switched to `envy::prefixed` , thanks alot for helping with this

2025-01-04 10:09 UTC, AyushAgrawal-A2 commented on quadratic-files/src/config.rs
> +fn default_host() -> String {
same as above

2025-01-07 19:39 UTC, ddimaria approved these changes

2025-01-13 21:55 UTC, davidkircos commented on .github/workflows/staging-create-stack.yml
> +    name: Create Stack - Preview
Small thing, can you rename these all "Preview - [name]" easier to read in the summary list on Github

2025-01-14 02:54 UTC, AyushAgrawal-A2 commented on .github/workflows/staging-create-stack.yml
> +    name: Create Stack - Preview
done

2025-01-14 17:03 UTC, davidkircos commented on .github/workflows/qa-close.yml
> +# todo(ayush): after moving all open PRs to new infra, add branches:-qa to this workflow
just set to qa, i'll clean up all the old stacks

2025-01-14 20:14 UTC, merged