feat: style & rename cell type outlines toggle
quadratichq/quadratic pull request #279
Opened 2023-02-16 20:20 UTC by jimniels

Style the toggle in the upper right to make it hint more at its function (rather than a generic, label-less toggle).

Also, once #277 gets merged, the function of this toggle is less about "cell type" outlines and more about the outlines behind a specific kind of cell, e.g. code/formulas, so my suggestion is we actually rename it to be "Show code cell outlines".

- [x] New toggle in app bar with tooltip
- [x] New name in tooltip, "Show code cell outlines"
- [ ] New name elsewhere in app (command palette, top bar dropdown)

![Feb-16-2023 13-08-39](https://user-images.githubusercontent.com/1316441/219477219-e98447f2-e1e9-498a-a40e-c73262fc3f20.gif)

---

Design notes:

I tried a couple different design ideas for this as a toggle

<img width="538" alt="CleanShot 2023-02-16 at 13 17 31@2x" src="https://user-images.githubusercontent.com/1316441/219477511-69fe5e9c-e931-4971-b06e-ad108b943144.png">

But ultimately felt that an icon in the same size/shape as the others in the toolbar was most effective.

For the on/off mode, rather than a fill or color change, I went with a dashed line. I tried a version where we color the "on" state, but it didn't quite feel appropriate and in line with how we use that color elsewhere in the app (which is a primary color and not necessarily a stateful color — though it is that way on the switches). I'm on the fence on this, but the current code keeps the icon the same color regardless of state (and only changes the shape).

![Feb-16-2023 13-12-36](https://user-images.githubusercontent.com/1316441/219477655-95ba4a9b-eda0-43a1-a879-c1ed997201d1.gif)

2023-02-28 06:11 UTC, davidkircos commented
@jimniels My thought for this one is lets go ahead with the rename and skip the Icon change. Keep the switch (for now).

2023-02-28 23:28 UTC, davidkircos requested changes

2023-02-28 23:28 UTC, davidkircos commented on src/ui/menus/TopBar/TopBar.tsx
> +const CustomSwitch = styled(Switch)(({ theme }) => ({
Move this component to a different file.

2023-02-28 23:28 UTC, davidkircos commented on src/ui/menus/TopBar/TopBar.tsx
> +      backgroundImage: `url('data:image/svg+xml;utf8,<svg width="18" height="18" viewBox="0 0 18 18" fill="none" xmlns="http://www.w3.org/2000/svg"><path fill="white" d="M6.2998 13.5L1.7998 9L6.2998
It seems like the icons could be a little bit smaller.

Also with the primary blue the switch really draws attention. Could you maybe do an outlined button with the icon?

2023-02-28 23:28 UTC, davidkircos commented on src/ui/menus/TopBar/TopBar.tsx
> +const CustomSwitch = styled(Switch)(({ theme }) => ({
Generally, I think the switch design is excellent! Nice job with the icon.

2023-03-01 19:26 UTC, jimniels commented on src/ui/menus/TopBar/TopBar.tsx
> +      backgroundImage: `url('data:image/svg+xml;utf8,<svg width="18" height="18" viewBox="0 0 18 18" fill="none" xmlns="http://www.w3.org/2000/svg"><path fill="white" d="M6.2998 13.5L1.7998 9L6.2998
Just pushed up a change that inverts the color so it's not so attention-grabbing. Here's what it looks like, what do you think?

![Mar-01-2023 12-24-29](https://user-images.githubusercontent.com/1316441/222243783-9269f4f5-0b31-4446-a44c-ca12c1f70295.gif)

2023-03-02 18:05 UTC, jimniels commented on src/ui/menus/TopBar/TopBar.tsx
> +      backgroundImage: `url('data:image/svg+xml;utf8,<svg width="18" height="18" viewBox="0 0 18 18" fill="none" xmlns="http://www.w3.org/2000/svg"><path fill="white" d="M6.2998 13.5L1.7998 9L6.2998
Latest:
![Mar-02-2023 11-04-21](https://user-images.githubusercontent.com/1316441/222513900-95dbb20a-fc86-4f8b-a767-5653afea0390.gif)

2023-03-03 22:07 UTC, davidkircos approved these changes

2023-03-03 22:30 UTC, merged