Alignment
quadratichq/quadratic pull request #318
Opened 2023-02-25 17:55 UTC by davidfig

2023-02-26 17:20 UTC, davidkircos requested changes
Overflow bug when aligning right.

<img width="1710" alt="Screenshot 2023-02-26 at 10 07 23 AM" src="https://user-images.githubusercontent.com/3479421/221425952-009ac924-9484-4701-a12e-0118b4dc5a7e.png">

2023-02-26 17:38 UTC, davidkircos commented
@davidfig 

Numbers can not be aligned left (we should default to 'auto' then the user could force one to align left)
Strings that start with a number, but are not a number are also aligned right by default. Should only align right when the cell contains only a valid number.

![Feb-26-2023 10-36-14](https://user-images.githubusercontent.com/3479421/221426777-34c08b01-2130-4d94-8d75-7108018b9d78.gif)

2023-02-27 20:40 UTC, jimniels commented on src/ui/menus/CommandPalette/ListItems/Format.tsx
> +    label: 'Format: Align Left',
We should change these to match the labels we're using for bold/italitc which are prefixed with the word 'Text' and use sentence case, 

<img width="531" alt="CleanShot 2023-02-27 at 13 33 45@2x" src="https://user-images.githubusercontent.com/1316441/221679288-0ed3ea49-1771-4d78-ad56-c0b2523dfca0.png">

In other words:

- Text: Align left
- Text: Align right
- Text: Align center

(Also these live in a different file, see `src/ui/menus/CommandPalette/ListItems/Text.tsx`

2023-03-04 18:26 UTC, davidkircos requested changes
Partial review:
- Cells starting with a number that are not a number should be left aligned by default like text. "50 hello" should align to the left.
<img width="176" alt="Screenshot 2023-03-04 at 11 24 59 AM" src="https://user-images.githubusercontent.com/3479421/222922608-71a7159d-01cb-4913-a26d-064f87243703.png">

2023-03-04 19:24 UTC, davidfig commented
Turns out isNaN for strings is way more complicated than I thought. Here's the best solution based on my research:

```
// from https://stackoverflow.com/a/58550111
function isStringANumber(s: string): boolean {
  return s.trim() !== '' && !isNaN(s as any as number);
}
````

2023-03-05 04:00 UTC, davidkircos commented
@davidfig, that makes sense. For consistency, I also replaced the function that decides if a `cell.value` is a number in the `CellTextFormatter` with the same function. See this commit. https://github.com/quadratichq/quadratic/pull/318/commits/a7b374743c634f57c4e4debeca0de483e99959b1

However, there is still an issue. We need to check if the label is a number _before_ applying the CellTextFormatting, not after. Otherwise, adding something like Currency formatting changes the default alignment. See gif.
![Mar-04-2023 20-59-12](https://user-images.githubusercontent.com/3479421/222940905-20d2e258-3cb6-472d-ad5c-75b84cf35d4e.gif)

2023-03-05 16:46 UTC, davidkircos commented
@davidfig seeing some odd behavior with formatting jumping around when loading files. It also appears to be a bit of a performance hit when true rendering. When loading the Monte Carlo sim doc it seems to be rendering it a few times, and formatting jumps around (see gif)
![Mar-05-2023 09-45-18](https://user-images.githubusercontent.com/3479421/222973922-49d8999a-e52a-4396-be52-f432b464e256.gif)

2023-03-05 16:49 UTC, davidkircos commented on .env
> +REACT_APP_DEBUG=1
this will put debug mode on in prod. use `.env.local` to override which is in the gitignore

2023-03-20 20:47 UTC, davidkircos requested changes
Some text overlaps 

<img width="509" alt="CleanShot 2023-03-20 at 14 45 38@2x" src="https://user-images.githubusercontent.com/3479421/226461874-929a5509-acdf-45ac-a94f-33de7bdcccab.png">

Numbers too big to fit into a cell should not remain left-aligned. They should either right-align or default to exponents. What do you think?

2023-05-17 21:51 UTC, jimniels commented
Ok, I update this PR with the latest from main and resolved merge conflicts. After playing around with it sum, these are my thoughts:

## Big takeaway

I personally feel like we should start this feature super conservatively.

What do I mean by that? We provide the controls for alignment in the UI to the user but don't auto-align anything. Everything continues to be left-aligned by default. If the user wants to align something, they now have the controls but otherwise we're not taking a stance and implementing any features around auto-alignment based on cell data types.

Separately, we can file an issue where we track the kinds of things that feel like they should be aligned by default, e.g. cells that are only numbers, cells where the user starts typing `$` followed by numbers, etc., which all feels like maybe it relates to the concept of #22 too.

In short, I personally don't think we're quite ready to go any further in the product with alignment other than simply: allow the user to align things how they want.

## Small item

Editing a cell doesn't preserve alignment (feels like it should? you can do that with an `<input>` can you not)? If nothing else, we should make sure we do this in #454

## Conclusion

If we do the two items above, IMO it's ready to be merged.

2023-05-19 20:46 UTC, jimniels approved these changes
Once we remove the auto-alignment (per [this comment](https://github.com/quadratichq/quadratic/pull/318#issuecomment-1552134373)) I'm good with these changes 👍

2023-05-20 12:50 UTC, merged