selection auto complete (WIP)
quadratichq/quadratic pull request #379
Opened 2023-03-26 17:04 UTC by davidfig

2023-04-11 19:50 UTC, davidkircos commented on src/gridGL/helpers/isStringANumber.ts
> +export const isStringANumber = (s: string) => {
There is another function that does this in the code base too. We should probably use the same function everywhere.

https://github.com/quadratichq/quadratic/blob/fa756a30deca0c84e912b633b4c92b4f6afb81d0/src/grid/formatting/cellTextFormatter.ts#L6

2023-04-11 19:50 UTC, davidkircos commented on src/gridGL/helpers/isStringANumber.ts
> +export const isStringANumber = (s: string) => {
I feel like we resolved this in the `alignment` branch, but that hasn't been merged yet

2023-04-11 19:51 UTC, davidkircos commented on src/theme/colors.ts
> +  boxCellsAlpha: 0.5,
@jimniels I'd love to get your feedback on these colors

2023-04-17 22:59 UTC, davidkircos requested changes
@davidfig Attempting to auto complete an empty range results in the app crashing 

<img width="325" alt="CleanShot 2023-04-17 at 16 58 55@2x" src="https://user-images.githubusercontent.com/3479421/232628070-e502ff5f-3cd6-4d19-a41a-214f21692b17.png">

2023-04-18 00:53 UTC, jimniels commented
![image](https://user-images.githubusercontent.com/1316441/232641167-9d018225-fc8b-4c53-8573-b80a0266651d.png)

To me, it feels a bit strange that the current selection gets highlighted as "remove" even when nothing is being removed.

I feel like I would expect red if we're removing, green if we're adding, and none if we're not doing either.

![image](https://user-images.githubusercontent.com/1316441/232641089-cabf030c-6833-4a55-ad70-145dd1c4619b.png)

2023-04-20 23:07 UTC, jimniels commented
### Style changes

After playing with this some more, and looking at what excel/sheets do, I feel like a good interaction style here is to keep the blue outline for additive dragging, and then a red outline at the point when a subtractive drag is taking place.

![Apr-20-2023 17-00-21](https://user-images.githubusercontent.com/1316441/233504414-1600d262-fd01-4f3c-b356-82a460aa58f1.gif)

This means that, when dragging the selection for a single cell, you'll never see the "remove" red highlight, because you're never doing a subtractive drag with just one cell.

![Apr-20-2023 17-05-17](https://user-images.githubusercontent.com/1316441/233504922-ed62ef04-60e4-4745-82aa-40c080b43d9d.gif)


**Outstanding bug**: this is not working for horizontal dragging. Will have to investigate why the logic is wrong. The positioning seems to be triggering at the wrong place, as you can see here:

![Apr-20-2023 16-57-29](https://user-images.githubusercontent.com/1316441/233504502-7e98e76d-830f-438a-8a0b-106138da7a79.gif)

### Deleting one, then two or more

When deleting a range down to 2 or more, things work as expected:

![deleting-to-2-or-more](https://user-images.githubusercontent.com/1316441/233504655-38334ba8-70bd-48be-b9c9-6c82a4269d64.gif)

But when deleting a range down to a single cell, it doesn't work:

![deleting-to-1](https://user-images.githubusercontent.com/1316441/233504607-8d085907-2b72-4c32-93ce-0cd01e97f1fa.gif)

2023-04-22 13:22 UTC, davidfig commented on src/gridGL/helpers/isStringANumber.ts
> +export const isStringANumber = (s: string) => {
copy & pasted

2023-04-22 14:32 UTC, jimniels commented
Deleting a range down to one cell still doesn't work

https://user-images.githubusercontent.com/1316441/233504607-8d085907-2b72-4c32-93ce-0cd01e97f1fa.gif

2023-04-22 14:33 UTC, jimniels commented
horizontal dragging still doesn't highlight red cells properly as you drag

![Apr-22-2023 08-33-27](https://user-images.githubusercontent.com/1316441/233790890-c31182e2-ba3a-48d6-bab8-09354acfa09c.gif)

2023-04-22 14:36 UTC, jimniels requested changes
horizontal dragging still doesn't highlight red cells properly as you drag column by column

![Apr-22-2023 08-33-27](https://user-images.githubusercontent.com/1316441/233790890-c31182e2-ba3a-48d6-bab8-09354acfa09c.gif)

Deleting a range down to one cell still doesn't work

<img src=https://user-images.githubusercontent.com/1316441/233504607-8d085907-2b72-4c32-93ce-0cd01e97f1fa.gif />

2023-04-24 17:58 UTC, davidkircos approved these changes

2023-04-24 18:00 UTC, merged