Replaced Input with Div + contenteditable
quadratichq/quadratic pull request #454
Opened 2023-04-30 13:01 UTC by davidfig

2023-05-08 17:46 UTC, jimniels commented
Changing formatting while you're editing characters in the cell works but doesn't apply to the saved cell when you hit enter.

For example, take a cell and begin editing it and hit `CMD` + `I` to make the text italic. It appears italic in the contenteditable but once you hit "ENTER" the saved value doesn't have italics applied (presumably it's only applying the italics to the contenteditable element and not the attribute of the cell itself)

![May-08-2023 11-38-50](https://user-images.githubusercontent.com/1316441/236892824-5197cb37-c805-4d3e-991c-0860e72e7036.gif)

You can see this play out if you try to apply formatting to only certain parts of the text of a cell but not others

![May-08-2023 11-42-15](https://user-images.githubusercontent.com/1316441/236893651-f99f216e-b4ee-4e47-8b61-1e5603676bba.gif)

I looked at excel (on web) to see what they do. They do appear to allow formatting to independent parts of text in a cell, though some of their formatting gets lost between editing/saving change too ha

![May-08-2023 11-43-38](https://user-images.githubusercontent.com/1316441/236893810-d0be6e32-7fba-4315-853f-4dc0e4799dae.gif)

Sheets also allows formatting to independent pieces of text

![May-08-2023 11-45-48](https://user-images.githubusercontent.com/1316441/236894074-edd72c17-a04f-4150-ad5d-4bcfc1053448.gif)

2023-05-08 18:57 UTC, jimniels commented
📝 Playing with this functionality in Excel and Sheets, I noticed that when you begin to edit a cell, the regular cursor highlight disappears and the cursor style outline applies around the entire box that's in focus.

For example, notice how in Sheets the little square in the bottom right disappears when you're editing (so you can't "drag/autocomplete" while editing a cell). The active cell gets highlighted with the style of the cursor but without the draggable circle.

![May-08-2023 12-48-28](https://user-images.githubusercontent.com/1316441/236907734-af7e3d04-bc0a-468e-8aac-80922ab16ab3.gif)

Same thing happens in Excel:

![May-08-2023 12-52-28](https://user-images.githubusercontent.com/1316441/236907903-81252e2b-970a-43d1-97c2-209cff51e72f.gif)

In quadratic, however, as you edit, the draggable cursor stays on screen and stays fixed on the original width of the cell regardless of how much text is being entered.

![May-08-2023 12-48-41](https://user-images.githubusercontent.com/1316441/236908288-1acde559-7df1-46ad-bdd4-94a11d5e58b3.gif)

I feel like I would expect quadratic to act similar to these other apps, e.g. when a cell becomes active for editing, the "drag" cursor disappears and the _entire length of the input_ gets the focus style of the active cell. Example mockup:

<img width="684" alt="CleanShot 2023-05-08 at 12 56 26@2x" src="https://user-images.githubusercontent.com/1316441/236908787-ee6c1e69-1167-47b9-ab7d-5181acabd736.png">

2023-05-08 19:05 UTC, jimniels commented on src/gridGL/interaction/CellInput.tsx
> +  }, [format]);
Is putting this in `useMemo` getting us something here? Why not have `fontFamily` be a normal piece of derived state, e.g.

```js
let fontFamily = 'OpenSans';
if (format.italic && format.bold) {
  fontFamily = 'OpenSans-BoldItalic';
} else if (format.italic) {
  fontFamily = 'OpenSans-Italic';
} else if (format.bold) {
  fontFamily = 'OpenSans-Bold';
}
```

I think this is causing some kind of bug because _when you're edit a cell without a background_, the font appears as Open Sans

<img width="658" alt="CleanShot 2023-05-08 at 13 04 44@2x" src="https://user-images.githubusercontent.com/1316441/236910262-85cc3408-a9bb-4be6-95fc-16c10353fc39.png">

2023-05-08 19:11 UTC, jimniels commented
🐞 (small) there's a tiny but noticeable overflow when you edit a cell with a background that happens when you go into "edit" mode on a cell. Note how, upon entering to edit the cell, the background color overflows the width of the cell.

![May-08-2023 13-09-54](https://user-images.githubusercontent.com/1316441/236911519-b6a7c853-587a-427e-a103-1f9e6d6e013a.gif)

2023-05-13 13:13 UTC, davidfig commented on src/gridGL/interaction/CellInput.tsx
> +  }, [format]);
Doesn't get us very much, but I'm not sure how it causes a bug. I'll switch it, though.

2023-05-16 19:49 UTC, jimniels commented
🐞 [This comment](https://github.com/quadratichq/quadratic/pull/454#issuecomment-1538903220) seems to have been fixed in most places, but I am still seeing it in a few contexts. Like this one: this is from the default example file.

<img width="1043" alt="CleanShot 2023-05-16 at 13 46 30@2x" src="https://github.com/quadratichq/quadratic/assets/1316441/79a7b311-eeb0-439f-8b8e-6c37a567886a">

When you click to edit the cell, the background goes longer than the cell

![May-16-2023 13-47-21](https://github.com/quadratichq/quadratic/assets/1316441/4ead92ae-09ae-46ed-a9e7-bdc8e48d6cfe)

Honestly doesn't seem like the biggest of deals, as it's working as expected across most cells (click to edit, and it's the size of the current cell) but in this one particular case it's longer than the current cell for some reason.

2023-05-16 19:52 UTC, jimniels commented
🐞 When you add spaces to the beginning of a cell, it's like the spaces aren't the same width between the cell input and the cell on the grid (when you go to edit it, the spacing isn't the same width)

![May-16-2023 13-51-24](https://github.com/quadratichq/quadratic/assets/1316441/7bbf373a-1c5e-446a-a999-f7c2a8041342)

2023-05-16 20:06 UTC, jimniels commented
🐞 If you format a cell with a background color, that background color doesn't extend the width of the cell input. It gets cut off. [Note how excel and sheets](https://github.com/quadratichq/quadratic/pull/454#issuecomment-1538880796) both have the cell input's style go the width of its contents only once you hit "Enter" and it goes into the grid does it truncate the background to the width of the cell.

![](https://user-images.githubusercontent.com/1316441/236907734-af7e3d04-bc0a-468e-8aac-80922ab16ab3.gif)

That is not how Quadratic works. Quadratic cuts off the background color while you're editing the cell.

![May-16-2023 14-02-34](https://github.com/quadratichq/quadratic/assets/1316441/d6a0fd98-9f3b-480e-b0d6-9aded7051470)

It makes sense to me that we mimic how excel/sheets work where formatting is preserved to fit the contents of the cell input (and can truncate once the user hits 'Enter')

2023-05-16 20:30 UTC, jimniels commented
🐞 This appears to be a bug with what's in prod, so I suppose if you want to file an issue and talk about it outside the scope of this PR, that's fine by me?

Maybe the background of a cell input, if not set, should be white? That way when you have two cells next to each other whose contents overlap as you edit, the text remains legible 

![May-16-2023 14-26-59](https://github.com/quadratichq/quadratic/assets/1316441/9688a90f-42ab-476c-b327-b3a270d6d31e)

I would expect it to work like this (example from Sheets)

![May-16-2023 14-28-53](https://github.com/quadratichq/quadratic/assets/1316441/679ee5e8-0876-45e4-ab1d-a3eb88636ae9)

2023-05-16 20:37 UTC, jimniels commented
🐞 I'm still seeing this bug where, sometimes, when I click outside of the cell input after having typed something, my cursor acts like i'm on a mousedown, so as I drag the cursor it's making a selection on the grid as I move my mouse (even though i'm not holding down the mouse).

Having a hard time reproducing it, but it's happening on and off. Will report back when I nail down a reproducible cause....

2023-05-21 15:49 UTC, davidkircos commented
Played around with this for a few minutes. It seems to work great! I noticed a small visual bug where the cursor sometimes has a gap with the background color.

https://github.com/quadratichq/quadratic/assets/3479421/28d70942-db3a-49eb-8836-b529a7062a9e

2023-05-22 18:02 UTC, jimniels commented
🐞 When you have two cells next to each other and the first one's length is longer than itself _and the one next to it_, then when you edit the one next to it, the first one's overflow becomes visible.

![May-22-2023 11-58-44](https://github.com/quadratichq/quadratic/assets/1316441/c049770e-d1b0-4a0e-8598-9b32125fa995)

That seemed like a bug to me, but I double checked excel/sheets to see how they do it and they don't allow the clipping of other cells to become visibile when you're editing a cell. So it is a bug in my mind. This is what I would expect (from Sheets):

![May-22-2023 11-58-07](https://github.com/quadratichq/quadratic/assets/1316441/e1737c4f-2312-4d09-bb94-ccd946feff97)

2023-05-22 18:06 UTC, HactarCE commented
Ctrl+scroll doesn't zoom in when my cursor is over the ContentEditable

2023-05-22 20:16 UTC, jimniels commented
Zooming while your cursor is over the cell input is doesn't appear to be specific to this PR. It's happening in prod today. We can probably file a separate issue for that apart from this chunk of work.

2023-05-30 18:34 UTC, jimniels requested changes
I'm still seeing these two bugs:

1. [This comment](https://github.com/quadratichq/quadratic/pull/454#issuecomment-1557664457)
2. [This comment](https://github.com/quadratichq/quadratic/pull/454#issuecomment-1550272965)

2023-06-12 16:56 UTC, merged