Strip formatting on paste while in CellInput
quadratichq/quadratic pull request #606
Opened 2023-07-12 05:37 UTC by davidfig

Closes #601.

2023-07-12 21:24 UTC, davidkircos commented on src/gridGL/interaction/CellInput.tsx
> +    // event.clipboardData.setData('text', result.replaceAll('\n', ''));
@davidfig should this line be removed?

2023-07-12 21:25 UTC, davidkircos commented on src/gridGL/interaction/CellInput.tsx
> +    const text = event.clipboardData.getData('text');
does this work on all browsers?

2023-07-12 21:27 UTC, davidkircos requested changes
Have a few comments and questions on the PR

Functionality seems to work great!

2023-07-12 21:27 UTC, davidkircos commented on src/gridGL/interaction/CellInput.tsx
> +    const text = event.clipboardData.getData('text');
Could It be cleaner to watch for value to change and strip all non supported chars?

Quadratic only supports a small set of chars at the moment, alphanumeric, and symbols. Maybe we should clean the input of everything that isn't supported on the grid?

2023-07-12 21:28 UTC, davidfig commented on src/gridGL/interaction/CellInput.tsx
> +    const text = event.clipboardData.getData('text');
Just tried it on Firefox and Edge. Pretty standard API.

2023-10-26 19:01 UTC, davidkircos commented
added to `next`

2023-10-26 19:01 UTC, closed without merging