Rust implementation of clipboard
quadratichq/quadratic pull request #681
Opened 2023-09-02 16:48 UTC by davidfig

2023-09-03 16:40 UTC, davidkircos commented
I haven't really reviewed it, but it is very fast!

2023-09-04 20:36 UTC, HactarCE requested changes
See comments; we probably need to use `RegionRef` (or something equivalent) instead of `Rect` to keep values associated with column & row IDs in case they move around.

2023-09-04 20:36 UTC, HactarCE commented on quadratic-core/src/controller/cells.rs
> +                }
Careful! `region` may be smaller than `rect` if some of the columns/rows don't exist, because we called `.existing_region()`. Destructure `region.size()` into `Some(region_size)`, then `let formats = vec![Column::new(); region_size.w];`

2023-09-04 20:36 UTC, HactarCE commented on quadratic-core/src/controller/transactions.rs
> +    },
This needs to store all of `region` and not infer the rectangle; if columns or rows move around or are deleted, then `pos` is useless.

This logic is already implemented in all the `SetCellFormats` handling, so I'd rather it not be duplicated. a couple options:
a) make `SetCellFormats` contain an optional array for _all_ formatting types.
b) submit multiple `SetCellFormats` operations when replacing formatting.

2023-09-04 20:36 UTC, HactarCE commented on quadratic-core/src/grid/column.rs
> +        }
no need to check whether `blocks.len() != 0` -- these functions will be fast in that case too.

2023-09-04 20:36 UTC, HactarCE commented on quadratic-core/src/controller/transactions.rs
> +}
`impl Default for TransactionSummary { }` and then use autocomplete to fill in the implementation.

But also, in this case we can use a `#[derive(Default)]` since all the fields are just defaults for their own types. Good idea to add a `default()`!

2023-09-14 18:51 UTC, HactarCE requested changes
very good! just 1 or 2 small changes and then I'll approve

2023-09-14 18:51 UTC, HactarCE commented on quadratic-core/src/controller/cells.rs
> +        ops.append(&mut self.clear_formatting_operations(sheet_id, rect));
`ops.extend(self.clear_formatting...)` is slightly cleaner (`&mut` right before throwing away a value feels a little weird)

2023-09-14 18:51 UTC, HactarCE commented on quadratic-core/src/grid/sheet.rs
> +        }
```rs
let column = self.get_column(pos.x)?;
let block = column.spills.get(pos.y)?;
```
no `.unwrap()` needed :)

2023-09-14 18:58 UTC, HactarCE approved these changes
yay!

2023-09-14 18:58 UTC, merged