Next currency
quadratichq/quadratic pull request #682
Opened 2023-09-04 15:45 UTC by davidfig

- [x] updated .fnt generating script to generate all unicode characters in a font
- [x] currency is converted to a number and proper formatting during user input

2023-09-04 19:34 UTC, HactarCE requested changes
I left some feedback. otherwise looks good!

2023-09-04 19:34 UTC, HactarCE commented on quadratic-core/src/controller/cells.rs
> +        if let Some((currency, number)) = Self::is_currency(&value) {
Perhaps this method should take `value: String` instead and then also convert to number? If you don't think we should do that right now, then this is fine as-is.

2023-09-04 19:34 UTC, HactarCE commented on quadratic-core/src/controller/cells.rs
> +        }
`if matches!(value, CellValue::Text(_))` or `if let CellValue::Text(_) = value` are preferred since they'll both error in case we ever change `"text"` to something else.

2023-09-04 19:34 UTC, HactarCE commented on quadratic-core/src/controller/cells.rs
> +        }
Even better here is `let CellValue::Text(s) = value else { return None; }` since we need `s` later on.

2023-09-04 19:34 UTC, HactarCE commented on quadratic-core/src/controller/cells.rs
> +        if s.len() == 0 {
`if s.is_empty()`

2023-09-04 19:34 UTC, HactarCE commented on quadratic-core/src/controller/cells.rs
> +        let possible_currency = s.chars().next().unwrap();
`let Some(first_char) = s.chars().next()?;` will return `None` if there is no first character, and then you don't even need the check above.

2023-09-04 19:34 UTC, HactarCE commented on quadratic-core/src/controller/cells.rs
> +            let split: Vec<&str> = s.split(possible_currency).collect();
Use `if let Some(number) = s.strip_prefix(possible_currency)`.

Consider rewriting this whole logic to loop over the currency symbols (which will happen anyway in `.contains()`) and try `.strip_prefix()` on each one.

2023-09-04 19:34 UTC, HactarCE commented on quadratic-core/src/controller/cells.rs
> +            if split.len() == 2 {
In general, prefer `if let Some(number) = splits.get(1)`

2023-09-04 19:34 UTC, HactarCE commented on quadratic-core/src/controller/cells.rs
> +    fn is_currency(value: &CellValue) -> Option<(String, f64)> {
I would prefer a name like `unpack_currency()`. Reading `is_.*` makes me think the function will return a boolean.

2023-09-04 19:34 UTC, HactarCE commented on quadratic-core/src/grid/formatting.rs
> +
This feels like a plain struct to me that doesn't have any implementation details to hide -- ok to just make these fields public and construct it with `NumericFormat { ... }` instead of using `NumericFormat::new(...)`?

2023-09-05 11:12 UTC, davidfig commented on quadratic-core/src/controller/cells.rs
> +        None
Good catch. Moved to CellValue.

2023-09-05 11:18 UTC, davidfig commented on quadratic-core/src/controller/cells.rs
> +        if let Some((currency, number)) = Self::is_currency(&value) {
That makes more sense.

2023-09-13 04:05 UTC, HactarCE requested changes

2023-09-13 04:05 UTC, HactarCE commented on quadratic-core/src/values/convert.rs
> +            CellValue::Number(n) => Ok(n.to_f64().unwrap()),
Actually we should change this whole impl to `impl<'a> TryFrom<&'a CellValue> for BigDecimal` and then change all the formula functions to operate on `BigDecimal` ...

2023-09-13 04:05 UTC, HactarCE commented on quadratic-core/src/values/convert.rs
> +            CellValue::Number(n) => Ok(n.to_f64().unwrap()),
I can take on that in another PR. In the meantime, formulas just won't preserve precision well.

2023-09-13 04:05 UTC, HactarCE commented on quadratic-core/src/values/convert.rs
> +            CellValue::Number(n) => Ok(n.ne(&BigDecimal::from_str(&"0.0").unwrap())),
[`n.is_zero()`](https://docs.rs/bigdecimal/latest/bigdecimal/struct.BigDecimal.html#method.is_zero)

2023-09-13 04:05 UTC, HactarCE commented on quadratic-core/src/values/mod.rs
> +// #[cfg_attr(feature = "js", derive(ts_rs::TS))]
remove

2023-09-13 04:05 UTC, HactarCE commented on quadratic-core/src/values/mod.rs
> +    // }
same as other one, not needed anymore!

2023-09-13 04:05 UTC, HactarCE commented on quadratic-core/src/wasm_bindings/mod.rs
> +        if let Some(n) = BigDecimal::parse_bytes(&string.clone().into_bytes(), 10) {
`BigDecimal::from_str_radix(&string, 10)`

2023-09-13 12:34 UTC, davidfig commented on quadratic-core/src/bin/export_types.rs
> +        // grid::CodeCellRunResult,
We actually need some of them. I'll pare them down and leave what's needed. (I cheated and used some any's as a short-term workaround.)

2023-09-13 12:48 UTC, davidfig commented on quadratic-core/src/grid/sheet.rs
> +        }
Wow. That was pretty terrible. Much better now.

2023-09-13 12:53 UTC, davidfig commented on quadratic-core/src/values/array.rs
> +                    .unwrap(),
I think I was having problems with ::from working earlier (for some reason). Much better.

2023-09-13 13:32 UTC, merged