Port auto complete to rust
quadratichq/quadratic pull request #690
Opened 2023-09-11 20:44 UTC by ddimaria

- [x] Basic shell for the `expand_down` functionality
- [ ] Complete `expand_down` functionality
- [ ] Add tests for `expand_down` functionality
- [ ] Repeat for `expand_up`, `expand_left`, and `expand right`
- [ ] Implement `shrink_horizontal` and `shrink_vertical`
- [ ] Add tests for `shrink_horizontal` and `shrink_vertical` functionality

2023-09-25 20:57 UTC, davidkircos commented
Expanding a series down and right doesn't expand the series to neighboring columns.

![Sep-25-2023 14-56-29](https://github.com/quadratichq/quadratic/assets/3479421/1733a40c-e593-47ad-b153-4249899da46d)

2023-09-26 01:35 UTC, davidkircos requested changes
- Expand series doesn't have the same behavior as production

Rust:
![CleanShot 2023-09-25 at 19 32 48](https://github.com/quadratichq/quadratic/assets/3479421/011e0ea4-d3f0-4372-942e-1eac62d401e0)
Prod:
![CleanShot 2023-09-25 at 19 33 23](https://github.com/quadratichq/quadratic/assets/3479421/f4842ba6-7dc2-4c72-983c-f6fa48a20ae4)

- Does not expand into negative space 

Rust:
![CleanShot 2023-09-25 at 19 34 35](https://github.com/quadratichq/quadratic/assets/3479421/a802a293-f1f7-4cdc-b354-cf984a77e480)
Prod:
![CleanShot 2023-09-25 at 19 35 12](https://github.com/quadratichq/quadratic/assets/3479421/1de0138f-f06c-48d5-a531-2b59673e88f9)

2023-10-01 15:41 UTC, davidkircos commented on quadratic-core/src/controller/auto_complete.rs
> +        range: Rect,
Which one is which? Consider renaming variables.

Chat GPT recommends `start_rect` and `end_rect`

2023-10-01 15:41 UTC, davidkircos commented on quadratic-core/src/controller/auto_complete.rs
> +    pub fn shrink(&mut self, sheet_id: SheetId, delete_range: Rect) -> Vec<Operation> {
The only public function is `expand`? The rest of these are only used as helper functions and should not be called outside of `expand`?

2023-10-01 15:47 UTC, ddimaria commented on quadratic-core/src/controller/auto_complete.rs
> +    pub fn shrink(&mut self, sheet_id: SheetId, delete_range: Rect) -> Vec<Operation> {
I made them public to be able to be tested by criterion (more info [here](https://bheisler.github.io/criterion.rs/book/user_guide/known_limitations.html)).  I'm happy to change them for now, though I think I may need to benchmark to see the bottleneck you're experiencing in large files in finer detail.

2023-10-01 15:49 UTC, ddimaria commented on quadratic-core/src/controller/auto_complete.rs
> +        range: Rect,
It's the rectangle that represents the selection.  I agree that it's not a great variable name.  `selection` seems to make a lot of sense for the name.  Does that work?

2023-10-01 15:49 UTC, ddimaria commented on quadratic-core/src/controller/auto_complete.rs
> +        range: Rect,
or `selected`

2023-10-01 15:52 UTC, davidkircos commented on quadratic-core/src/controller/auto_complete.rs
> +    pub fn shrink(&mut self, sheet_id: SheetId, delete_range: Rect) -> Vec<Operation> {
I'm guessing the bottleneck is in JS and not rust

2023-10-01 15:53 UTC, davidkircos commented on quadratic-core/src/controller/auto_complete.rs
> +        range: Rect,
'selection_start' and 'selection_end'?

2023-10-01 15:56 UTC, ddimaria commented on quadratic-core/src/controller/auto_complete.rs
> +        range: Rect,
Can you elaborate on the reasoning behind the `_start` and `_end`?

2023-10-01 22:53 UTC, HactarCE requested changes
Overall, looks good! As usual, just a bunch of nitpicks

2023-10-01 22:53 UTC, HactarCE commented on quadratic-core/src/test_util.rs
> +        expected.clone(),
`.clone()` shouldn't be necessary. Equality comparison works on references, and `assert_eq!()` automatically takes a reference. If just `expected` doesn't work, then use `*expected`

2023-10-01 22:53 UTC, HactarCE commented on quadratic-core/src/wasm_bindings/controller/auto_complete.rs
> +    /// Expand the contents of the selected rectangle up to the specified row.
This isn't super clear -- there's no `row` parameter in function, and it should work both horizontally & vertically. Maybe:
> Extend or shrink the contents of `rect` to `range` by inferring patterns.

2023-10-01 22:53 UTC, HactarCE commented on quadratic-core/src/controller/auto_complete.rs
> +#[derive(PartialEq)]
`Debug`, `Copy`, `Clone`, and `Eq` would be nice, altho we don't need them right now.

2023-10-01 22:53 UTC, HactarCE commented on quadratic-core/src/controller/auto_complete.rs
> +pub fn cell_values_in_rect(&selection: &Rect, sheet: &Sheet) -> Result<Array> {
This'll be super useful in formula eval as well, so it should probably be defined directly on `Grid`.

2023-10-01 22:53 UTC, HactarCE commented on quadratic-core/src/controller/auto_complete.rs
> +        (grid_controller.clone(), sheet_id)
Why clone here?

2023-10-01 22:53 UTC, HactarCE commented on quadratic-core/src/test_util.rs
>  pub fn print_table(grid_controller: GridController, sheet_id: SheetId, range: &Rect) {
This should definitely take a reference! We don't want to clone the whole universe just to get some debug output

2023-10-01 22:53 UTC, HactarCE commented on quadratic-core/src/test_util.rs
>  pub fn print_table(grid_controller: GridController, sheet_id: SheetId, range: &Rect) {
Also, `Rect` is `Copy` so no need to take a reference

2023-10-01 22:53 UTC, HactarCE commented on quadratic-core/src/grid/series.rs
> +];
I think it makes sense to support support lowercase, uppercase, and titlecase for every string series. It might be worth it to find a way to do this without duplicating each series several times, or perhaps not.

2023-10-01 22:53 UTC, HactarCE commented on quadratic-core/src/grid/series.rs
> +    let text_series: Vec<Vec<&str>> = vec![
Not need to allocate a new vec for each series. This should work:
```rs
let text_series: &[&[&str]] = &[
    &ALPHABET_LOWER,
    ...
];
```

2023-10-02 13:54 UTC, ddimaria commented on quadratic-core/src/test_util.rs
> +        expected.clone(),
Good catch!  This is done.

2023-10-02 13:56 UTC, ddimaria commented on quadratic-core/src/wasm_bindings/controller/auto_complete.rs
> +    /// Expand the contents of the selected rectangle up to the specified row.
I just changed this var name to match the changes I did in the other file and incorporated your suggestion:

> Extend and/or shrink the contents of selection to range by inferring patterns.

2023-10-02 13:58 UTC, ddimaria commented on quadratic-core/src/controller/auto_complete.rs
> +        (grid_controller.clone(), sheet_id)
This is a leftover before a refactor into a function.  Removed.

2023-10-02 14:01 UTC, ddimaria commented on quadratic-core/src/grid/series.rs
> +];
I agree.  I think I kept the behavior of the legacy code, but we should be actually ignoring case on a series match IMO.  We could just store the lower case and force lower case on the input when matching?  That would be less code, but slightly less efficient.

2023-10-02 14:04 UTC, ddimaria commented on quadratic-core/src/test_util.rs
>  pub fn print_table(grid_controller: GridController, sheet_id: SheetId, range: &Rect) {
That GridController copy was an oversight, thanks for catching it.  Also, IDK Rect was copy...odd that clippy didn't pick that up. These changes have been made.

2023-10-02 14:12 UTC, ddimaria commented on quadratic-core/src/grid/series.rs
> +    let text_series: Vec<Vec<&str>> = vec![
Thanks, this is done.

2023-10-02 15:40 UTC, davidkircos commented on quadratic-core/src/controller/auto_complete.rs
> +        range: Rect,
Doesn't one Rect represent the starting selection and one represent the ending selection for the expand/autocomplete operation?

2023-10-02 15:44 UTC, ddimaria commented on quadratic-core/src/controller/auto_complete.rs
> +        range: Rect,
The `rect` represents the initial selection (or 1st cursor) and the `range` represents the expansion/shrinkage area _inclusive_ of the `rect`.

2023-10-02 19:02 UTC, davidkircos approved these changes

2023-10-02 19:02 UTC, merged