Next firefox clipboard
quadratichq/quadratic pull request #693
Opened 2023-09-15 15:19 UTC by davidfig

- [x] better support for Firefox copy/pasting
- [x] full keyboard shortcut clipboard support for firefox (with fallback for menu copying)

2023-09-15 15:49 UTC, davidkircos requested changes

2023-09-15 15:49 UTC, davidkircos commented on src/grid/actions/clipboard/clipboard.ts
> +  debugTimeReset();
Did you mean to leave these debug function calls in?

2023-09-15 15:49 UTC, davidkircos commented on src/grid/actions/clipboard/clipboard.ts
> +    console.warn('clipboardData is not defined');
When would this happen? Do we want to report to sentry or is this sometimes expected?

2023-09-15 15:49 UTC, davidkircos commented on src/gridGL/interaction/keyboard/keyboardClipboard.ts
> -  }
cut no longer works on Chrome on Mac via Command + X

2023-09-15 15:49 UTC, davidkircos commented on src/grid/actions/clipboard/clipboard.ts
> +  if (navigator.clipboard?.read) {
The clipboard logic here is a bit complex and platform-specific. Can you add some detailed comments so when we edit this in a year, we remember why we did what we did?

2023-09-15 15:49 UTC, davidkircos commented on src/gridGL/pixiApp/PixiApp.ts
> +    document.addEventListener('paste', pasteFromClipboardEvent);
Probably forgot to add an event listener for `cut`

2023-09-15 15:49 UTC, davidkircos commented on src/grid/actions/clipboard/clipboard.ts
> +let lastCopy: string | undefined = undefined;
code style, define at the top of the file?

2023-09-15 15:49 UTC, davidkircos commented on src/grid/actions/clipboard/clipboard.ts
> +let lastCopy: string | undefined = undefined;
Does it make sense to use local storage so you can copy/paste between tabs on Firefox?

2023-09-15 15:49 UTC, davidkircos commented on src/grid/actions/clipboard/clipboard.ts
> +    console.log('copy to PNG is not supported in Firefox (yet)');
Ah, we should maybe hide this feature if it just doesn't work in FireFox. If that's the case I think it's beyond the scope of this PR and we should just create an issue for later.

2023-09-15 17:52 UTC, davidfig commented on src/grid/actions/clipboard/clipboard.ts
> +  debugTimeReset();
Yes. These only run when `debugShowTime = true`

2023-09-15 17:52 UTC, davidfig commented on src/grid/actions/clipboard/clipboard.ts
> +    console.warn('clipboardData is not defined');
This should not happen in any browser we support. But it's optional in the types.

2023-09-15 19:30 UTC, davidkircos commented on src/grid/actions/clipboard/clipboard.ts
> +  if (navigator.clipboard) {
Should we use the `fullClipboardSupport ` function here?

2023-09-15 19:30 UTC, davidkircos commented on src/grid/actions/clipboard/clipboard.ts
> +  if (navigator.clipboard?.read) {
use `fullClipboardSupport`?

2023-09-16 12:53 UTC, davidfig commented on src/grid/actions/clipboard/clipboard.ts
> +  localforage.setItem(clipboardLocalStorageKey, html);
This was how Figma handled it, so I thought it was helpful.

2023-09-16 12:53 UTC, davidfig commented on src/grid/actions/clipboard/clipboard.ts
> +  if (navigator.clipboard) {
Sure

2023-09-16 12:57 UTC, davidfig commented on src/grid/actions/clipboard/clipboard.ts
> +  if (navigator.clipboard?.read) {
This one is slightly different depending on when and how Firefox decides to support clipboards.

2023-09-18 17:04 UTC, davidkircos approved these changes

2023-09-18 20:18 UTC, merged