Next address clippy lints
quadratichq/quadratic pull request #713
Opened 2023-09-29 18:00 UTC by ddimaria

2023-10-03 19:21 UTC, ddimaria commented
@HactarCE I think you might be the interested party here.  Most are just simple lint fixes, but some required a bit more.

2023-10-03 22:40 UTC, HactarCE requested changes
Almost everything looks good! Good judgement about where to allow lints.

2023-10-03 22:40 UTC, HactarCE commented on quadratic-core/src/formulas/functions/operators.rs
> -            (1 * -6 + -2 - 1 * (-3_i32).pow(2_u32.pow(3))).to_string(),
These `1 *`s are intentional, to match the formula string.

2023-10-03 22:40 UTC, HactarCE commented on quadratic-core/src/grid/mod.rs
> +            return Err(anyhow!("sheet name already in use"));
Use `bail!("sheet name already in use");`

2023-10-03 22:40 UTC, HactarCE commented on quadratic-core/src/values/array_size.rs
> +        self.w.get() == 0 && self.h.get() == 0
This is impossible. `ArraySize` must be nonempty, so having this method is misleading. I'd be ok with it if the doc comment says that it always returns `false` because arrays are always nonempty.

2023-10-03 22:40 UTC, HactarCE commented on quadratic-core/src/values/mod.rs
> +    #[allow(clippy::should_implement_trait)]
Yeahhhh ... technically we _should_ implement the trait but I didn't because then we'd need an explicit type instead of just `impl Iterator<...>`. This is fine.

2023-10-04 14:17 UTC, ddimaria commented on quadratic-core/src/formulas/functions/operators.rs
> -            (1 * -6 + -2 - 1 * (-3_i32).pow(2_u32.pow(3))).to_string(),
I reverted and added an override for this function.

2023-10-04 14:19 UTC, ddimaria commented on quadratic-core/src/grid/mod.rs
> +            return Err(anyhow!("sheet name already in use"));
This is done, I keep forgetting this macro, very useful...thanks! (I've mostly used thiserror on other projects)

2023-10-04 14:23 UTC, ddimaria commented on quadratic-core/src/values/array_size.rs
> +        self.w.get() == 0 && self.h.get() == 0
Clippy complains if you implement a `len()` function that it's idiomatic to have an accompanying `is_empty()` function.  You made both w & h a NonZeroU32, so this is just clippy not being smart enough.  I'll just remove the function and add an override as that seems most appropriate.

2023-10-04 14:41 UTC, ddimaria reviewed
All changes have been implemented.

2023-10-04 14:43 UTC, merged