Spills
quadratichq/quadratic pull request #778
Opened 2023-11-08 13:13 UTC by davidfig

- [x] spills when array overflows
- [ ] spills change for SetCellValues operation
- [ ] spills change for SetCodeCell operation

2023-11-14 15:25 UTC, ddimaria commented on quadratic-core/Cargo.toml
> +[dependencies.chrono]
Can you just add to dependencies rather than it's own section?
```toml
chrono = { version = "0.4", features = ["serde", "wasmbind"] }
```

2023-11-14 15:27 UTC, ddimaria commented on quadratic-core/src/controller/operation.rs
> -            Operation::None => write!(fmt, "None"),
Nice, I never knew what that None Operation was all about.

2023-11-14 15:28 UTC, ddimaria commented on quadratic-core/src/controller/operations.rs
> +                        if let Some(_) = sheet.get_cell_value(pos) {
nit: `sheet.get_cell_value(pos).is_some()` if you don't care about the inner value.

2023-11-14 15:32 UTC, ddimaria commented on quadratic-core/src/controller/operations.rs
> +                reverse_operations.push(Operation::SetCellFormats {
Ignore, I see what is going on here.  What was wrong with the old pattern of return reverse operations and just pushing to reverse_operations just once?

2023-11-14 15:36 UTC, ddimaria commented on quadratic-core/src/controller/spills.rs
> +mod test {
Nice tests 💯

2023-11-16 14:30 UTC, davidfig commented on quadratic-core/src/controller/spills.rs
> +            if let Some(column) = sheet.get_column(pos.x) {
i'd like that, but they're all dependent on the previous one

2023-11-21 04:33 UTC, HactarCE requested changes

2023-11-21 04:33 UTC, HactarCE commented on quadratic-core/src/grid/sheet/code.rs
> +                                // if spilled only set the top left cell
Wait wait wait, does "spilled" mean that the code cell has expanded into a whole array? Or does it mean that the code cell _wants_ to expand but can't?

2023-11-21 04:33 UTC, HactarCE commented on quadratic-core/src/grid/sheet/code.rs
> +    pub fn get_spill(&self, cell_ref: CellRef) -> Option<CellRef> {
This needs a doc comment, especially with a symmetric-looking signature like `CellRef -> Option<CellRef>`

2023-11-21 04:33 UTC, HactarCE commented on quadratic-core/src/grid/sheet/code.rs
> +                        rect.translate(pos.x, pos.y);
```rs
let pos = self.cell_ref_to_pos(*code_cell_ref)?;
let array_size = code_cell.output_size()?;
let rect = Rect::from_pos_and_size(pos, array_size);
```

2023-11-21 04:33 UTC, HactarCE commented on quadratic-core/src/grid/sheet/code.rs
> +                        }
`CellRef` is `Copy`, so no need to clone it.
```rs
region.contains(cell_ref).then(|| {
    (code_cell_ref, code_cell.clone())
})
```

2023-11-21 04:33 UTC, HactarCE commented on quadratic-core/src/grid/sheet/code.rs
> +                    false
This boolean is weird. Shouldn't we never end up in this branch because 1x1 outputs should never have spill errors? In that case, we don't need the condition at all -- just let the general logic do its thing. This line should never be run and is untestable and implies that this code has more cases than it does.

2023-11-21 19:29 UTC, ddimaria commented on quadratic-core/src/controller/operations.rs
> +                    .insert(CellSheetsModified::new(sheet_id, pos));
@davidfig I'm going to hold off on this until we can discuss it more as CellSheetsModified is in many places.

2023-11-21 20:06 UTC, ddimaria commented on quadratic-core/src/controller/operations.rs
>                  let old_code_cell_value = sheet.get_code_cell_from_ref(cell_ref).cloned();
@davidfig let's talk about this one.  I got about 30 mins into this one and it turned into a big refactor.

2023-11-21 21:40 UTC, ddimaria commented on quadratic-core/src/grid/code.rs
> +    pub fn output_rect(&self) -> Option<Rect> {
@davidfig I made this change, but also had to fix a test at the bottom of the file.  I want to make sure the output is what is expected?

Before:
```rust
assert_eq!(
    code_cell.output_rect(),
    Some(Rect::new_span(Pos { x: 0, y: 0 }, Pos { x: 10, y: 11 }))
);
```

After:
```rust
assert_eq!(
    code_cell.output_rect(),
    Some(Rect::new_span(Pos { x: 0, y: 0 }, Pos { x: 9, y: 10 }))
);
```

2023-11-21 22:08 UTC, ddimaria commented on quadratic-core/src/controller/spills.rs
> +                summary,
This makes sense.  Maybe these functions should be implemented on TransactionInProgress then we can just reference `self`?  Thoughts @davidfig?

2023-11-21 22:09 UTC, davidfig commented on quadratic-core/src/grid/sheet/code.rs
> +                                // if spilled only set the top left cell
spills is what code cell is currently in the cell

2023-11-22 14:59 UTC, ddimaria commented on quadratic-core/src/grid/sheet/code.rs
> +                    false
@davidfig what are your thoughts on this?

2023-11-22 15:09 UTC, ddimaria commented on quadratic-core/src/grid/sheet/code.rs
> +            .sorted_by(|a, b| a.1.last_modified.cmp(&b.1.last_modified))
I agree, this string date should only exist as a string in the file format an not in the underlying struct.  I looked through the Rust code and this in the only place that we're even evaluating the `last_modified` date.  I have a feeling that dates and clocks will become important if we move toward CRDTs.  I'm going to create an issue to convert `last_modified` to an actual date.

2023-11-27 18:22 UTC, ddimaria commented on quadratic-core/src/controller/operations.rs
>                  let old_code_cell_value = sheet.get_code_cell_from_ref(cell_ref).cloned();
Added a TODO in the code

2023-11-27 18:22 UTC, ddimaria commented on quadratic-core/src/controller/operations.rs
> +                    .insert(CellSheetsModified::new(sheet_id, pos));
Added a TODO in the code

2023-11-27 18:29 UTC, ddimaria commented on quadratic-core/src/grid/sheet.rs
> +                let y = y + j as i64;
Added a TODO in the code

2023-11-27 18:34 UTC, ddimaria commented on quadratic-core/src/grid/sheet/code.rs
> +            .sorted_by(|a, b| a.1.last_modified.cmp(&b.1.last_modified))
Implement `sorted_by_key` here

2023-11-27 18:35 UTC, ddimaria commented on quadratic-core/src/grid/sheet/code.rs
> +            .sorted_by(|a, b| a.1.last_modified.cmp(&b.1.last_modified))
Added a TODO in the `CodeCellValue` struct to convert `last_modified` to a timestamp

2023-11-27 18:48 UTC, davidkircos approved these changes

2023-11-27 18:48 UTC, merged