0 properly outputs as string for python
quadratichq/quadratic pull request #803
Opened 2023-11-14 19:38 UTC by davidfig

Fixes #802

2023-11-14 19:44 UTC, ddimaria approved these changes
Code looks good!

2023-11-14 19:59 UTC, davidkircos requested changes

2023-11-14 19:59 UTC, davidkircos commented on src/web-workers/pythonWebWorker/python.ts
> +  return typeof input === 'string' ? input : typeof input === 'undefined' ? '' : input.toString();
Why do we have to check if it's undefined if the typescript says it's always either `(input: string | number)`?

2023-11-14 20:00 UTC, davidkircos commented on src/web-workers/pythonWebWorker/python.ts
> +  return typeof input === 'string' ? input : typeof input === 'undefined' ? '' : input.toString();
Could you use `if` instead of nested ternary? difficult to read

2023-11-14 20:01 UTC, davidkircos commented on src/web-workers/pythonWebWorker/python.ts
> -              entry.map((entry: String | number) => (entry ? entry.toString() : ''))
if it can't be undefined, we can always call entry.toString()?

2023-11-16 14:12 UTC, davidfig commented on src/web-workers/pythonWebWorker/python.ts
> +  return typeof input === 'string' ? input : typeof input === 'undefined' ? '' : input.toString();
The typescript is wrong. It can be undefined. I'll add it as an option, and remove the ternary (although I do think it's cool).

2023-11-16 15:41 UTC, ddimaria approved these changes

2023-11-16 15:56 UTC, davidkircos approved these changes

2023-11-16 17:10 UTC, merged