feat: export grid selection as csv
quadratichq/quadratic pull request #836
Opened 2023-11-17 16:53 UTC by ddimaria

- [x] Select rectangle on grid, select Download Selection as CSV, downloads CSV with grid file name and the file name.
- [x] Add Rust tests

2023-11-20 19:04 UTC, davidkircos commented on src/grid/controller/Grid.ts
> +    console.log(rectangleToRect(sheets.sheet.cursor.getRectangle()));
remove log

2023-11-20 19:05 UTC, davidkircos approved these changes

2023-11-20 23:12 UTC, jimniels requested changes
Looks pretty good. Love this feature! Just a few things to cleanup then it LGTM

2023-11-20 23:12 UTC, jimniels commented on src/grid/actions/downloadSelectionAsCSV.ts
> +};
We have been slowly working on a centralized place for defining a bunch of actions/labels that get re-used like this.  (We haven't done it yet for "Copy selection as PNG" but should...)

It's probably worth sticking this in there and re-using it?

`src/actions.ts` is the file

Something like

```js
// src/actions.ts
export const downloadSelectionAsCSV = {
  label: 'Download selection as CSV",
  run: (fileName: string) => {
    const csv = grid.exportCsvSelection();
    downloadFile(fileName, csv, 'text/plain', 'csv');
  }
};
```

2023-11-20 23:12 UTC, jimniels commented on src/grid/actions/downloadSelectionAsCSV.ts
> +};
Also minor casing thing:

We have it named `exportCsvSelection` in another file but `downloadSelectionAsCSV` here. We should either capitalize "CSV" everywhere, or stick to camelCase.

I would say we stick to camelCase, as we'll do things like `fileId` elsewhere, so this should be `downloadSelectionAsCsv`

2023-11-20 23:12 UTC, jimniels commented on src/ui/menus/CommandPalette/ListItems/Edit.tsx
> +  },
Per the comment about centralizing things in `src/actions.ts` here you could import the label/action and re-use it.

2023-11-20 23:12 UTC, jimniels commented on src/ui/menus/TopBar/SubMenus/DataMenu.tsx
> +          />
We're using a different icon in this menu than the other menus.

![CleanShot 2023-11-20 at 15 44 30@2x](https://github.com/quadratichq/quadratic/assets/1316441/127f9302-87ea-48cd-9f63-57e27b5db94b)

We should use the same icon we're using in the other menus

![CleanShot 2023-11-20 at 15 44 36@2x](https://github.com/quadratichq/quadratic/assets/1316441/5703d085-0653-4b73-8f1c-fdb71d168fb6)

![CleanShot 2023-11-20 at 15 44 45@2x](https://github.com/quadratichq/quadratic/assets/1316441/4e08068e-addd-4a3e-811e-b5939a2ab853)

2023-11-21 00:33 UTC, jimniels approved these changes
One thing (update icon) and then LGTM 👍

2023-11-21 00:33 UTC, jimniels commented on src/ui/menus/TopBar/SubMenus/DataMenu.tsx
> +          />
@davidkircos can you update the icon on this one to use the same one we're using in the command palette? Looks like it's `<Download />`

2023-11-21 03:12 UTC, merged