feat: improve bottom bar stats functionality
quadratichq/quadratic pull request #861
Opened 2023-11-21 21:13 UTC by jimniels

The current implementation of the bottom bar outputs a number that is _really_ big.

![CleanShot 2023-11-21 at 14 00 58@2x](https://github.com/quadratichq/quadratic/assets/1316441/1f409530-09a5-4c30-939e-e929a9eada5f)

Excel caps this number at 9 digits beyond the decimal

![CleanShot 2023-11-21 at 14 01 25@2x](https://github.com/quadratichq/quadratic/assets/1316441/422a2476-e221-4050-9e9c-742360214554)

So we do the same thing:

![CleanShot 2023-11-21 at 14 01 08@2x](https://github.com/quadratichq/quadratic/assets/1316441/564e1f68-7010-4dc1-bc0b-834dc960cc9b)

Also: excel provides the ability for you to click and copy the values in the bottom bar. This allows you to do the same thing in Quadratic.

![CleanShot 2023-11-21 at 14 08 22](https://github.com/quadratichq/quadratic/assets/1316441/71f4b857-0e5d-4fe4-8864-69257b3b19c0)

2023-11-21 22:03 UTC, davidkircos requested changes

2023-11-21 22:03 UTC, davidkircos commented on src/ui/menus/BottomBar/SelectionSummary.tsx
> +    navigator.clipboard.writeText(valueToCopy).then(() => {
I think this causes problems in firefox? I think we have to check the `fullClipboardSupport` flag first.

2023-11-22 03:19 UTC, jimniels commented on src/ui/menus/BottomBar/SelectionSummary.tsx
> +    navigator.clipboard.writeText(valueToCopy).then(() => {
`navigator.clipboard.writeText` works in all browsers. It's [the `navigator.clipboard.write` you gotta watch out for](https://developer.mozilla.org/en-US/docs/Web/API/Clipboard).

This code works for me in Firefox for mac



https://github.com/quadratichq/quadratic/assets/1316441/afce00c4-ffd8-463b-8adb-70cbd165d283

2023-11-22 03:28 UTC, davidkircos approved these changes

2023-11-22 03:28 UTC, merged